import { z } from 'zod';
import * as f from './followup';
import type { RouteDef } from './routes';
import * as s from './schemas';

/**
 * R3 follow-up routes (07 §2b, §2c, §2d). Every one refuses when the Follow-up extra is off for
 * the centre (403 `extra_not_enabled`; a centre the caller cannot see stays 404, 10 §2).
 */
const def = <T extends RouteDef>(r: T) => r;
const Id = z.object({ id: z.uuid() });
const CentreRule = z.object({ id: z.uuid(), code: z.string().max(40) });
const EXTRA = { status: 403, code: 'extra_not_enabled' };
const user = 'user' as const;

export const followupRoutes = {
  // ── Teacher (07 §2b) ──────────────────────────────────────────────────────────
  teacherToday: def({
    name: 'getTeacherToday',
    method: 'get',
    path: '/v1/teachers/me/today',
    summary: 'T01: next session, reminders from confirmed records, the record due, what needs you',
    tag: 'records',
    rules: ['FUP-REC-01', 'BR-APR-08', 'CF-34'],
    auth: user,
    response: f.TeacherToday,
    errors: [EXTRA],
  }),
  roster: def({
    name: 'getRoster',
    method: 'get',
    path: '/v1/groups/{id}/roster',
    summary: 'T10: paid seats of the group, last 4 sessions (`none` = no confirmed record), flags',
    tag: 'records',
    rules: ['FUP-REC-09', 'BR-APR-07'],
    auth: user,
    params: Id,
    response: f.RosterList,
    errors: [EXTRA],
  }),
  listRecords: def({
    name: 'listSessionRecords',
    method: 'get',
    path: '/v1/groups/{id}/session-records',
    summary: "The group's session records, newest first",
    tag: 'records',
    rules: ['FUP-REC-12'],
    auth: user,
    params: Id,
    response: f.SessionRecordList,
    errors: [EXTRA],
  }),
  openRecord: def({
    name: 'openSessionRecord',
    method: 'post',
    path: '/v1/groups/{id}/session-records',
    summary: 'Open the draft for a session that took place (201 new, 200 the existing one)',
    tag: 'records',
    rules: ['FUP-REC-02', 'BR-APR-07'],
    auth: user,
    idempotent: true,
    params: Id,
    body: f.OpenRecordBody,
    response: f.SessionRecord,
    status: 201,
    errors: [EXTRA, { status: 422, code: 'session_not_recordable' }],
  }),
  getRecord: def({
    name: 'getSessionRecord',
    method: 'get',
    path: '/v1/session-records/{id}',
    summary: 'A record with its corrections, flags and correction requests (T05, A14)',
    tag: 'records',
    rules: ['FUP-REC-12', 'FUP-REC-08'],
    auth: user,
    params: Id,
    response: f.SessionRecord,
    errors: [EXTRA],
  }),
  saveDraft: def({
    name: 'saveSessionRecordDraft',
    method: 'patch',
    path: '/v1/session-records/{id}',
    summary: 'Save the draft: a score above the maximum is blocked, never capped',
    tag: 'records',
    rules: ['FUP-REC-02', 'FUP-REC-03', 'BR-APR-09'],
    auth: user,
    idempotent: true,
    params: Id,
    body: f.SaveRecordBody,
    response: f.SessionRecord,
    errors: [
      EXTRA,
      { status: 409, code: 'record_confirmed' },
      { status: 422, code: 'score_out_of_range' },
      { status: 422, code: 'score_for_absent' },
      { status: 422, code: 'assessment_required' },
      { status: 422, code: 'unknown_student' },
    ],
  }),
  confirmRecord: def({
    name: 'confirmSessionRecord',
    method: 'post',
    path: '/v1/session-records/{id}/confirm',
    summary: 'Approval 1: the teacher confirms; the rules run on the confirmed record',
    tag: 'records',
    rules: ['FUP-REC-05', 'FUP-REC-07', 'FUP-RUL-03', 'BR-APR-01', 'BR-APR-08'],
    auth: user,
    idempotent: true,
    params: Id,
    response: f.SessionRecord,
    errors: [
      EXTRA,
      { status: 409, code: 'record_confirmed' },
      { status: 409, code: 'identity_unresolved' },
    ],
  }),
  addCorrection: def({
    name: 'addCorrection',
    method: 'post',
    path: '/v1/record-entries/{id}/corrections',
    summary: 'Correct a confirmed entry with a reason; the original stays; rules re-run',
    tag: 'records',
    rules: ['FUP-REC-08', 'INV-09'],
    auth: user,
    idempotent: true,
    params: Id,
    body: f.CorrectionBody,
    response: f.Correction,
    status: 201,
    errors: [
      EXTRA,
      { status: 409, code: 'record_not_confirmed' },
      { status: 422, code: 'reason_required' },
    ],
  }),
  requestCorrection: def({
    name: 'requestCorrection',
    method: 'post',
    path: '/v1/session-records/{id}/correction-requests',
    summary: 'CF-34: the owner asks the teacher to correct a confirmed record',
    tag: 'records',
    rules: ['CF-34'],
    auth: user,
    idempotent: true,
    params: Id,
    body: f.CorrectionRequestBody,
    response: f.CorrectionRequest,
    status: 201,
    errors: [EXTRA, { status: 409, code: 'record_not_confirmed' }],
  }),
  closeCorrectionRequest: def({
    name: 'closeCorrectionRequest',
    method: 'post',
    path: '/v1/correction-requests/{id}/close',
    summary: "CF-34: the group's teacher closes a request without a correction",
    tag: 'records',
    rules: ['CF-34'],
    auth: user,
    idempotent: true,
    params: Id,
    response: f.CorrectionRequest,
    errors: [EXTRA],
  }),
  student: def({
    name: 'getStudentDetail',
    method: 'get',
    path: '/v1/students/{id}',
    summary: 'T12: attendance strip, trends per series only, notes, flags',
    tag: 'records',
    rules: ['FUP-REC-11'],
    auth: user,
    params: Id,
    response: f.StudentDetail,
    errors: [EXTRA],
  }),
  addNote: def({
    name: 'addStudentNote',
    method: 'post',
    path: '/v1/students/{id}/notes',
    summary: 'An internal note (≤ 500 characters); a saved note can raise `repeated_concern`',
    tag: 'records',
    rules: ['FUP-REC-10', 'BR-APR-13', 'BR-APR-08'],
    auth: user,
    idempotent: true,
    params: Id,
    body: f.NoteBody,
    response: f.Note,
    status: 201,
    errors: [EXTRA, { status: 422, code: 'too_long' }],
  }),
  suggestNote: def({
    name: 'suggestNoteForParent',
    method: 'post',
    path: '/v1/notes/{id}/suggest-for-parent',
    summary: 'Send a note to staff for a parent update (never to the parent)',
    tag: 'records',
    rules: ['FUP-REC-10'],
    auth: user,
    idempotent: true,
    params: Id,
    response: f.Note,
    errors: [EXTRA],
  }),

  // ── Voice (07 §2b, docs/09) ───────────────────────────────────────────────────
  createVoiceNote: def({
    name: 'createVoiceNote',
    method: 'post',
    path: '/v1/voice-notes',
    summary: 'A voice note for a draft record; returns a short-lived signed upload URL',
    tag: 'voice',
    rules: ['FUP-VOI-01', 'FUP-VOI-02'],
    auth: user,
    idempotent: true,
    body: f.VoiceNoteBody,
    response: f.VoiceNote,
    status: 201,
    errors: [EXTRA, { status: 503, code: 'stt_unavailable' }],
  }),
  uploadVoiceAudio: def({
    name: 'uploadVoiceAudio',
    method: 'put',
    path: '/v1/voice-notes/{id}/audio',
    summary: 'The signed upload: raw audio bytes, stored encrypted (S3 SSE), deleted after 30 days',
    tag: 'voice',
    rules: ['FUP-VOI-02', 'BR-DAT-04'],
    auth: 'public',
    params: Id,
    response: f.VoiceNote,
    errors: [
      { status: 403, code: 'invalid_signature' },
      { status: 413, code: 'bad_audio' },
    ],
  }),
  voiceUploaded: def({
    name: 'voiceNoteUploaded',
    method: 'post',
    path: '/v1/voice-notes/{id}/uploaded',
    summary: 'The audio is in: `voice.uploaded` hands it to ai-service',
    tag: 'voice',
    rules: ['FUP-VOI-02'],
    auth: user,
    idempotent: true,
    params: Id,
    response: f.VoiceNote,
    errors: [EXTRA, { status: 409, code: 'not_uploaded' }],
  }),
  retryVoice: def({
    name: 'retryVoiceNote',
    method: 'post',
    path: '/v1/voice-notes/{id}/retry',
    summary: 'Send the kept audio to speech-to-text again',
    tag: 'voice',
    rules: ['FUP-VOI-06'],
    auth: user,
    idempotent: true,
    params: Id,
    response: f.VoiceNote,
    errors: [EXTRA, { status: 409, code: 'not_uploaded' }],
  }),
  extraction: def({
    name: 'getVoiceExtraction',
    method: 'get',
    path: '/v1/voice-notes/{id}/extraction',
    summary: 'V02: 202 while processing; then the proposal (a draft, never a record)',
    tag: 'voice',
    rules: ['FUP-VOI-03', 'FUP-VOI-06', 'BR-APR-05'],
    auth: user,
    params: Id,
    response: z.union([f.VoiceExtraction, f.VoicePending]),
    errors: [
      EXTRA,
      { status: 503, code: 'stt_unavailable' },
      { status: 503, code: 'stt_failed' },
      { status: 503, code: 'stt_timeout' },
    ],
  }),
  resolveIdentity: def({
    name: 'resolveVoiceIdentity',
    method: 'post',
    path: '/v1/voice-extractions/{id}/resolve-identity',
    summary: 'T07: the teacher picks the student (one of the candidates); Link never guesses',
    tag: 'voice',
    rules: ['FUP-VOI-04'],
    auth: user,
    idempotent: true,
    params: Id,
    body: f.ResolveIdentityBody,
    response: f.VoiceExtraction,
    errors: [EXTRA, { status: 422, code: 'not_a_candidate' }],
  }),
  discardItem: def({
    name: 'discardVoiceItem',
    method: 'post',
    path: '/v1/voice-extractions/{id}/discard-item',
    summary: 'Drop an item: nothing from it is saved',
    tag: 'voice',
    rules: ['FUP-VOI-04'],
    auth: user,
    idempotent: true,
    params: Id,
    body: f.DiscardItemBody,
    response: f.VoiceExtraction,
    errors: [EXTRA],
  }),
  voiceResult: def({
    name: 'postVoiceResult',
    method: 'post',
    path: '/v1/internal/voice-results/{id}',
    summary: 'ai-service → core-api (service token): the proposal or failure for a note',
    tag: 'internal',
    rules: ['FUP-VOI-02', 'FUP-VOI-04'],
    auth: 'public',
    params: Id,
    body: f.VoiceResultBody,
    response: null,
  }),

  // ── Cases (07 §2c) ────────────────────────────────────────────────────────────
  listCases: def({
    name: 'listCases',
    method: 'get',
    path: '/v1/cases',
    summary: 'A02: follow-ups of the caller’s centres that have the extra',
    tag: 'cases',
    rules: ['FUP-CAS-01', 'FUP-CAS-05'],
    auth: user,
    response: f.FollowupCasePage,
    errors: [EXTRA],
  }),
  getCase: def({
    name: 'getCase',
    method: 'get',
    path: '/v1/cases/{id}',
    summary: 'A03: why it appeared (rule, dates, who confirmed), the rule version, the timeline',
    tag: 'cases',
    rules: ['FUP-CAS-02', 'BR-APR-04'],
    auth: user,
    params: Id,
    response: f.FollowupCase,
    errors: [EXTRA],
  }),
  addAttempt: def({
    name: 'addCaseAttempt',
    method: 'post',
    path: '/v1/cases/{id}/attempts',
    summary: 'Record a contact and its result; kept open until confirmed (BR-APR-10)',
    tag: 'cases',
    rules: ['FUP-CAS-03', 'BR-APR-10'],
    auth: user,
    idempotent: true,
    params: Id,
    body: f.AttemptBody,
    response: f.FollowupCase,
    status: 201,
    errors: [EXTRA, { status: 409, code: 'case_closed' }],
  }),
  dismissCase: def({
    name: 'dismissCase',
    method: 'post',
    path: '/v1/cases/{id}/dismiss',
    summary: 'Dismiss with a reason; the flag stays in history and can be reopened',
    tag: 'cases',
    rules: ['FUP-CAS-04', 'BR-APR-14'],
    auth: user,
    idempotent: true,
    params: Id,
    body: f.DismissBody,
    response: f.FollowupCase,
    errors: [EXTRA, { status: 422, code: 'reason_required' }],
  }),
  reopenCase: def({
    name: 'reopenCase',
    method: 'post',
    path: '/v1/cases/{id}/reopen',
    summary: 'Reopen a dismissed or resolved follow-up',
    tag: 'cases',
    rules: ['FUP-CAS-04'],
    auth: user,
    idempotent: true,
    params: Id,
    response: f.FollowupCase,
    errors: [EXTRA],
  }),
  seatCheck: def({
    name: 'checkSeat',
    method: 'post',
    path: '/v1/cases/{id}/seat-check',
    summary: "V06: seats left in the teacher's other groups for the same subject (logged)",
    tag: 'cases',
    rules: ['FUP-MSG-05'],
    auth: user,
    idempotent: true,
    params: Id,
    response: f.SeatCheck,
    errors: [EXTRA],
  }),

  // ── Messages (07 §2c, §2d) ────────────────────────────────────────────────────
  listMessages: def({
    name: 'listMessages',
    method: 'get',
    path: '/v1/messages',
    summary: 'Parent messages of the caller’s centres (phones masked)',
    tag: 'messages',
    rules: ['FUP-MSG-01'],
    auth: user,
    response: f.ParentMessagePage,
    errors: [EXTRA],
  }),
  getMessage: def({
    name: 'getMessage',
    method: 'get',
    path: '/v1/messages/{id}',
    summary: 'A message with its grounded facts, status history and replies',
    tag: 'messages',
    rules: ['FUP-MSG-01', 'BR-APR-11'],
    auth: user,
    params: Id,
    response: f.ParentMessage,
    errors: [EXTRA],
  }),
  draftMessage: def({
    name: 'draftMessage',
    method: 'post',
    path: '/v1/messages/drafts',
    summary: 'Draft in Egyptian Arabic from confirmed facts only, each with its source',
    tag: 'messages',
    rules: ['FUP-MSG-01', 'BR-APR-13'],
    auth: user,
    idempotent: true,
    body: f.DraftBody,
    response: f.ParentMessage,
    status: 201,
    errors: [EXTRA],
  }),
  editMessage: def({
    name: 'editMessage',
    method: 'patch',
    path: '/v1/messages/{id}',
    summary: 'Edit a draft (text or tone); an approved message is locked',
    tag: 'messages',
    rules: ['FUP-MSG-02'],
    auth: user,
    idempotent: true,
    params: Id,
    body: f.EditMessageBody,
    response: f.ParentMessage,
    errors: [EXTRA, { status: 409, code: 'message_locked' }],
  }),
  approveMessage: def({
    name: 'approveMessage',
    method: 'post',
    path: '/v1/messages/{id}/approve',
    summary:
      'Approval 2: `messages.approve` + the tick; queued for the provider, or not sendable (opt-in, STOP)',
    tag: 'messages',
    rules: ['FUP-MSG-02', 'FUP-MSG-03', 'BR-APR-02', 'BR-APR-11', 'INV-11'],
    auth: user,
    idempotent: true,
    params: Id,
    body: f.ApproveBody,
    response: f.ParentMessage,
    errors: [
      EXTRA,
      { status: 403, code: 'forbidden' },
      { status: 409, code: 'message_locked' },
      { status: 422, code: 'check_required' },
    ],
  }),
  reviseMessage: def({
    name: 'reviseMessage',
    method: 'post',
    path: '/v1/messages/{id}/revise',
    summary: 'A new draft from an approved message (the approved one stays locked)',
    tag: 'messages',
    rules: ['FUP-MSG-02'],
    auth: user,
    idempotent: true,
    params: Id,
    response: f.ParentMessage,
    status: 201,
    errors: [EXTRA, { status: 409, code: 'still_draft' }],
  }),
  sentManually: def({
    name: 'markMessageSentManually',
    method: 'post',
    path: '/v1/messages/{id}/sent-manually',
    summary:
      '"I sent it": staff sent the approved text themselves — a contact attempt, never a delivery',
    tag: 'messages',
    rules: ['OD-56', 'BR-APR-11'],
    auth: user,
    idempotent: true,
    params: Id,
    response: f.ParentMessage,
    errors: [EXTRA, { status: 409, code: 'not_approved' }, { status: 409, code: 'already_sent' }],
  }),
  messagingWebhook: def({
    name: 'messagingWebhook',
    method: 'post',
    path: '/v1/webhooks/messaging/{provider}',
    summary:
      'WhatsApp provider → Link: delivery statuses and replies (signature first, deduped on event ID)',
    tag: 'webhooks',
    rules: ['BR-APR-11', 'BR-DAT-02', 'FUP-MSG-05'],
    auth: 'public',
    params: z.object({ provider: z.string().max(40) }),
    response: z.object({ ok: z.literal(true), outcome: z.string() }),
    errors: [{ status: 401, code: 'invalid_signature' }],
  }),

  // ── Owner web (07 §2c) ────────────────────────────────────────────────────────
  ownerToday: def({
    name: 'getCentreToday',
    method: 'get',
    path: '/v1/centres/{id}/today',
    summary: 'A01: due, overdue with owners, records complete over sessions that took place',
    tag: 'followup',
    rules: ['FUP-DSH-01', 'FUP-CAS-05', 'BR-APR-07'],
    auth: user,
    params: s.CentreParams,
    response: f.OwnerToday,
    errors: [EXTRA],
  }),
  centreStudents: def({
    name: 'listCentreStudents',
    method: 'get',
    path: '/v1/centres/{id}/students',
    summary: 'A13: one row per student and follow-up group',
    tag: 'followup',
    rules: ['FUP-DSH-02'],
    auth: user,
    params: s.CentreParams,
    response: f.CentreStudentPage,
    errors: [EXTRA],
  }),
  centreSessions: def({
    name: 'listCentreSessions',
    method: 'get',
    path: '/v1/centres/{id}/sessions',
    summary: 'A05: sessions of the last two weeks with their record status',
    tag: 'followup',
    rules: ['FUP-REC-12'],
    auth: user,
    params: s.CentreParams,
    response: f.CentreSessionPage,
    errors: [EXTRA],
  }),
  listRules: def({
    name: 'listRules',
    method: 'get',
    path: '/v1/centres/{id}/rules',
    summary: 'A07: the four rules, readable text, version history and any proposal',
    tag: 'followup',
    rules: ['FUP-RUL-01', 'FUP-RUL-02'],
    auth: user,
    params: s.CentreParams,
    response: f.RuleViewList,
    errors: [EXTRA],
  }),
  changeRule: def({
    name: 'changeRule',
    method: 'put',
    path: '/v1/centres/{id}/rules/{code}',
    summary: 'The owner: a new version. Staff: a proposal the owner approves (BR-APR-12)',
    tag: 'followup',
    rules: ['FUP-RUL-01', 'FUP-RUL-02', 'BR-APR-12'],
    auth: user,
    idempotent: true,
    params: CentreRule,
    body: f.RuleChangeBody,
    response: f.RuleView,
    errors: [EXTRA, { status: 422, code: 'validation_failed' }],
  }),
  approveRule: def({
    name: 'approveRuleChange',
    method: 'post',
    path: '/v1/centres/{id}/rules/{code}/approve',
    summary: 'Owner only: the proposal becomes the next version',
    tag: 'followup',
    rules: ['FUP-RUL-02', 'BR-APR-12'],
    auth: user,
    idempotent: true,
    params: CentreRule,
    response: f.RuleView,
    errors: [EXTRA, { status: 409, code: 'no_proposal' }],
  }),
  rejectRule: def({
    name: 'rejectRuleChange',
    method: 'post',
    path: '/v1/centres/{id}/rules/{code}/reject',
    summary: 'Owner only: the proposal is rejected; the version in force stays',
    tag: 'followup',
    rules: ['FUP-RUL-02'],
    auth: user,
    idempotent: true,
    params: CentreRule,
    response: f.RuleView,
    errors: [EXTRA, { status: 409, code: 'no_proposal' }],
  }),
  activity: def({
    name: 'getCentreActivity',
    method: 'get',
    path: '/v1/centres/{id}/activity',
    summary: 'A17: the append-only history of records, follow-ups, messages and access',
    tag: 'followup',
    rules: ['FUP-DSH-04'],
    auth: user,
    params: s.CentreParams,
    response: f.ActivityLog,
    errors: [EXTRA],
  }),

  // ── Parent (07 §2c, §2d) ──────────────────────────────────────────────────────
  parentUpdates: def({
    name: 'listParentUpdates',
    method: 'get',
    path: '/v1/me/updates',
    summary: 'P09: approved messages for the parent’s own children, from centres with the extra on',
    tag: 'messages',
    rules: ['FUP-MSG-08', 'OD-41', 'OD-58'],
    auth: user,
    response: f.ParentUpdatePage,
  }),
  centreGroups: def({
    name: 'listParentCentreGroups',
    method: 'get',
    path: '/v1/me/centre-groups',
    summary: "CF-39: the children's groups at centres with the extra (P09, marketplace off)",
    tag: 'messages',
    rules: ['CF-39'],
    auth: user,
    response: f.CentreGroupList,
  }),

  // ── Ask Link (07 §2c, D7): off in live mode unless a local LLM is configured (R3.4) ──
  assistantBriefing: def({
    name: 'getAssistantBriefing',
    method: 'get',
    path: '/v1/assistant/briefing',
    summary: 'V07: the open follow-ups, read from the data (503 when Ask Link is off)',
    tag: 'assistant',
    rules: ['FUP-DSH-05'],
    auth: user,
    response: z.unknown(),
    errors: [{ status: 503, code: 'assistant_unavailable' }],
  }),
  assistantTurn: def({
    name: 'assistantTurn',
    method: 'post',
    path: '/v1/assistant/turns',
    summary:
      'A turn as server-sent events: read tier only; names never reach the model; never acts',
    tag: 'assistant',
    rules: ['FUP-DSH-05', 'BR-APR-02'],
    auth: user,
    body: z.object({ text: z.string().max(2000) }),
    response: z.unknown(),
    errors: [{ status: 503, code: 'assistant_unavailable' }],
  }),
  assistantTranscribe: def({
    name: 'assistantTranscribe',
    method: 'post',
    path: '/v1/assistant/transcribe',
    summary: 'A spoken question → text through local speech-to-text (sample data only)',
    tag: 'assistant',
    rules: ['FUP-DSH-05'],
    auth: user,
    response: z.unknown(),
    errors: [
      { status: 503, code: 'assistant_unavailable' },
      { status: 503, code: 'stt_unavailable' },
    ],
  }),
} satisfies Record<string, RouteDef>;
