import { z } from 'zod';
import { followupRoutes } from './followup-routes';
import * as m from './market';
import * as $ from './money';
import { opsRoutes } from './ops';
import * as s from './schemas';

/**
 * One entry per endpoint (07 §2). Controllers mount these with `@Endpoint(routes.x)`; the OpenAPI
 * document is generated from this list, so a route cannot exist without its contract.
 */
export interface RouteDef {
  /** OpenAPI operationId. */
  name: string;
  method: 'get' | 'post' | 'put' | 'patch' | 'delete';
  /** OpenAPI path, `{param}` style. */
  path: string;
  summary: string;
  tag: string;
  /** Requirement / rule IDs (07 tables, 01). */
  rules: string[];
  /** `public` = no token; `user` = signed in (any role; handlers check the rest). */
  auth: 'public' | 'user';
  /**
   * Ops console routes (`/v1/ops/*`): the permission the caller's `link_ops` role must hold
   * (OD-37), or `any`. The guard checks OPS_IP_ALLOWLIST, the role and this permission.
   */
  ops?: 'ops.verify' | 'ops.moderate' | 'ops.finance' | 'any';
  /** 07 "Idem ✓": an Idempotency-Key is required and the first response is replayed. */
  idempotent?: boolean;
  /** Money endpoints also keep a durable copy in platform.idempotency_keys (07 §1). */
  money?: boolean;
  params?: z.ZodObject;
  query?: z.ZodObject;
  body?: z.ZodType;
  /** `null` = 204 No Content. */
  response: z.ZodType | null;
  status?: number;
  /** Problem codes this route can return (documented in OpenAPI). */
  errors?: { status: number; code: string }[];
}

const def = <T extends RouteDef>(r: T) => r;

export const routes = {
  // ── Auth and account ─────────────────────────────────────────────────────────
  otpRequest: def({
    name: 'requestOtp',
    method: 'post',
    path: '/v1/auth/otp/request',
    summary: 'Send a 6-digit SMS code (5 minutes; resend after 60 s)',
    tag: 'auth',
    rules: ['MKT-ACC-01'],
    auth: 'public',
    body: s.OtpRequestBody,
    response: s.OtpRequestResult,
    errors: [
      { status: 422, code: 'invalid_phone' },
      { status: 429, code: 'rate_limited' },
      { status: 429, code: 'resend_too_soon' },
    ],
  }),
  otpVerify: def({
    name: 'verifyOtp',
    method: 'post',
    path: '/v1/auth/otp/verify',
    summary:
      'Verify the code; returns the user and the tokens (body for the app, cookies for the web)',
    tag: 'auth',
    rules: ['MKT-ACC-01', 'MKT-ACC-02'],
    auth: 'public',
    body: s.OtpVerifyBody,
    response: s.OtpVerifyResult,
    errors: [
      { status: 422, code: 'invalid_phone' },
      { status: 422, code: 'otp_invalid' },
      { status: 422, code: 'otp_expired' },
      { status: 429, code: 'otp_locked' },
    ],
  }),
  refresh: def({
    name: 'refreshTokens',
    method: 'post',
    path: '/v1/auth/refresh',
    summary: 'Rotate the refresh token (30 days); reuse of an old one revokes the chain',
    tag: 'auth',
    rules: ['MKT-ACC-04'],
    auth: 'public',
    body: s.RefreshBody,
    response: s.TokenPair,
    errors: [{ status: 401, code: 'refresh_invalid' }],
  }),
  logout: def({
    name: 'logout',
    method: 'post',
    path: '/v1/auth/logout',
    summary: 'Revoke the refresh token and clear the cookies',
    tag: 'auth',
    rules: ['MKT-ACC-04'],
    auth: 'public',
    body: s.RefreshBody,
    response: null,
  }),
  me: def({
    name: 'getMe',
    method: 'get',
    path: '/v1/me',
    summary: 'Profile, roles, language, centres and teacher ID',
    tag: 'account',
    rules: ['MKT-ACC-03'],
    auth: 'user',
    response: s.Me,
  }),
  updateMe: def({
    name: 'updateMe',
    method: 'patch',
    path: '/v1/me',
    summary: 'Name and language',
    tag: 'account',
    rules: ['MKT-ACC-03'],
    auth: 'user',
    idempotent: true,
    body: s.UpdateMeBody,
    response: s.Me,
  }),
  addRole: def({
    name: 'addRole',
    method: 'post',
    path: '/v1/me/roles',
    summary: 'Add the role parent, teacher or centre_owner',
    tag: 'account',
    rules: ['MKT-ACC-02'],
    auth: 'user',
    idempotent: true,
    body: s.AddRoleBody,
    response: s.Me,
  }),
  consents: def({
    name: 'getConsents',
    method: 'get',
    path: '/v1/me/consents',
    summary: 'Current consents (latest event per kind; never cached)',
    tag: 'account',
    rules: ['BR-DAT-03'],
    auth: 'user',
    response: s.ConsentList,
  }),
  putConsent: def({
    name: 'putConsent',
    method: 'put',
    path: '/v1/me/consents',
    summary: 'Grant or withdraw one consent',
    tag: 'account',
    rules: ['BR-DAT-03'],
    auth: 'user',
    idempotent: true,
    body: s.PutConsentBody,
    response: s.ConsentList,
    errors: [{ status: 403, code: 'forbidden' }],
  }),
  children: def({
    name: 'listChildren',
    method: 'get',
    path: '/v1/me/children',
    summary: 'My children',
    tag: 'account',
    rules: ['MKT-ACC-05'],
    auth: 'user',
    response: s.ChildPage,
  }),
  addChild: def({
    name: 'addChild',
    method: 'post',
    path: '/v1/me/children',
    summary: 'Add a child (records the child_data_processing consent)',
    tag: 'account',
    rules: ['MKT-ACC-05', 'BR-DAT-03'],
    auth: 'user',
    idempotent: true,
    body: s.NewChildBody,
    response: s.Child,
    status: 201,
  }),
  myFeatures: def({
    name: 'getParentFeatures',
    method: 'get',
    path: '/v1/me/features',
    summary: 'Paid extras on for any centre where my children study',
    tag: 'features',
    rules: ['OD-58'],
    auth: 'user',
    response: s.CentreFeatures,
  }),
  featureFlags: def({
    name: 'getFeatureFlags',
    method: 'get',
    path: '/v1/feature-flags',
    summary:
      'Feature flags for the signed-in caller: global, merged with their own centre and teacher scopes',
    tag: 'features',
    rules: ['E0-09'],
    auth: 'user',
    response: s.FeatureFlags,
  }),

  // ── Reference data ───────────────────────────────────────────────────────────
  curricula: def({
    name: 'listCurricula',
    method: 'get',
    path: '/v1/curricula',
    summary: 'Curricula with their school years',
    tag: 'reference',
    rules: ['MKT-DSC-01'],
    auth: 'public',
    response: s.CurriculumList,
  }),
  subjects: def({
    name: 'listSubjects',
    method: 'get',
    path: '/v1/subjects',
    summary: 'Subjects, optionally for one curriculum and school year',
    tag: 'reference',
    rules: ['MKT-DSC-01'],
    auth: 'public',
    query: s.SubjectsQuery,
    response: s.SubjectList,
  }),

  // ── Centres ──────────────────────────────────────────────────────────────────
  centreApplication: def({
    name: 'applyCentre',
    method: 'post',
    path: '/v1/centre-applications',
    summary:
      'C01 join request. The centre and the owner role are created, verification pending, when this phone signs in',
    tag: 'centres',
    rules: ['MKT-CEN-01'],
    auth: 'public',
    idempotent: true,
    body: s.CentreApplicationBody,
    response: s.CentreApplicationResult,
    status: 201,
    errors: [
      { status: 422, code: 'consent_required' },
      { status: 422, code: 'invalid_phone' },
    ],
  }),
  staff: def({
    name: 'listStaff',
    method: 'get',
    path: '/v1/centres/{id}/staff',
    summary: 'Staff of this centre',
    tag: 'centres',
    rules: ['MKT-ACC-06'],
    auth: 'user',
    params: s.CentreParams,
    response: s.StaffList,
  }),
  inviteStaff: def({
    name: 'inviteStaff',
    method: 'post',
    path: '/v1/centres/{id}/staff',
    summary: 'Invite staff by phone, with permissions (owner only)',
    tag: 'centres',
    rules: ['MKT-ACC-06'],
    auth: 'user',
    idempotent: true,
    params: s.CentreParams,
    body: s.InviteStaffBody,
    response: s.StaffList,
    status: 201,
    errors: [
      { status: 403, code: 'forbidden' },
      { status: 422, code: 'invalid_phone' },
    ],
  }),
  centreFeatures: def({
    name: 'getCentreFeatures',
    method: 'get',
    path: '/v1/centres/{id}/features',
    summary: 'Paid extras for this centre',
    tag: 'features',
    rules: ['OD-58'],
    auth: 'user',
    params: s.CentreParams,
    response: s.CentreFeatures,
  }),
  teacherFeatures: def({
    name: 'getTeacherFeatures',
    method: 'get',
    path: '/v1/teachers/me/features',
    summary: 'Paid extras on for any centre the teacher works in',
    tag: 'features',
    rules: ['OD-58'],
    auth: 'user',
    response: s.CentreFeatures,
  }),

  // ── Teacher invites (decided 2026-10-09) ─────────────────────────────────────
  myInvites: def({
    name: 'listMyInvites',
    method: 'get',
    path: '/v1/me/invites',
    summary: 'Invitations from centres waiting for my answer',
    tag: 'account',
    rules: ['MKT-ACC-06'],
    auth: 'user',
    response: m.InviteList,
  }),
  acceptInvite: def({
    name: 'acceptInvite',
    method: 'post',
    path: '/v1/me/invites/{id}/accept',
    summary:
      'Accept a centre invitation; a teacher profile stays hidden until accepted and complete',
    tag: 'account',
    rules: ['MKT-ACC-06'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    response: m.InviteList,
  }),

  // ── Centres: profile, halls, schedule, auto-approve (C02, C03, C05) ──────────
  centreProfile: def({
    name: 'getCentreProfileEdit',
    method: 'get',
    path: '/v1/centres/{id}/profile',
    summary: 'C02 editing view: public fields, halls, completeness, badges, location under review',
    tag: 'centres',
    rules: ['MKT-CEN-02', 'CF-44'],
    auth: 'user',
    params: m.IdParams,
    response: m.CentreProfileEdit,
  }),
  patchCentre: def({
    name: 'patchCentre',
    method: 'patch',
    path: '/v1/centres/{id}',
    summary: 'Edit the profile (owner); a moved pin puts the location under review (CF-44)',
    tag: 'centres',
    rules: ['MKT-CEN-02', 'CF-44'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    body: m.CentrePatch,
    response: m.CentreProfileEdit,
    errors: [
      { status: 403, code: 'forbidden' },
      { status: 422, code: 'invalid_location' },
    ],
  }),
  halls: def({
    name: 'listHalls',
    method: 'get',
    path: '/v1/centres/{id}/rooms',
    summary: 'Halls with their weekly slots (C05)',
    tag: 'centres',
    rules: ['MKT-CEN-03'],
    auth: 'user',
    params: m.IdParams,
    response: m.HallList,
  }),
  addHall: def({
    name: 'addHall',
    method: 'post',
    path: '/v1/centres/{id}/rooms',
    summary: 'Add a hall (owner, CF-44): listed, the whole weekly grid open',
    tag: 'centres',
    rules: ['MKT-CEN-03', 'CF-44'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    body: m.NewHallBody,
    response: m.Hall,
    status: 201,
    errors: [{ status: 403, code: 'forbidden' }],
  }),
  patchHall: def({
    name: 'patchHall',
    method: 'patch',
    path: '/v1/rooms/{id}',
    summary: 'Edit a hall: one rent rule, seats never below a group in it, closed slots (owner)',
    tag: 'centres',
    rules: ['MKT-CEN-03'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    body: m.HallPatch,
    response: m.Hall,
    errors: [
      { status: 403, code: 'forbidden' },
      { status: 409, code: 'capacity_below_group' },
    ],
  }),
  schedule: def({
    name: 'getCentreSchedule',
    method: 'get',
    path: '/v1/centres/{id}/schedule',
    summary: 'C03: who uses which hall, seats filled, free slots, the next six working days',
    tag: 'centres',
    rules: ['MKT-CEN-04'],
    auth: 'user',
    params: m.IdParams,
    response: m.CentreSchedule,
  }),
  autoApprove: def({
    name: 'getAutoApprove',
    method: 'get',
    path: '/v1/centres/{id}/settings/auto-approve',
    summary: 'Auto-approve rules (off by default)',
    tag: 'centres',
    rules: ['MKT-HAL-05'],
    auth: 'user',
    params: m.IdParams,
    response: m.AutoApproveRules,
  }),
  putAutoApprove: def({
    name: 'putAutoApprove',
    method: 'put',
    path: '/v1/centres/{id}/settings/auto-approve',
    summary: 'Change the auto-approve rules (owner)',
    tag: 'centres',
    rules: ['MKT-HAL-05'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    body: m.AutoApproveRules,
    response: m.AutoApproveRules,
    errors: [{ status: 403, code: 'forbidden' }],
  }),

  // ── Room requests and bookings (J01–J03, C06) ────────────────────────────────
  roomSearch: def({
    name: 'searchRooms',
    method: 'get',
    path: '/v1/rooms/search',
    summary: 'J01: listed halls of verified centres with free slots, nearest first',
    tag: 'rooms',
    rules: ['MKT-HAL-01'],
    auth: 'user',
    query: m.RoomSearchQuery,
    response: m.RoomSearchList,
  }),
  rentEstimate: def({
    name: 'rentEstimate',
    method: 'post',
    path: '/v1/rooms/{id}/rent-estimate',
    summary: 'J02: rent, Link commission and what the teacher keeps (a pure calculation)',
    tag: 'rooms',
    rules: ['BR-BKG-07', 'OD-02'],
    auth: 'user',
    params: m.IdParams,
    body: m.RentEstimateBody,
    response: m.RentEstimate,
  }),
  requestRoom: def({
    name: 'requestRoom',
    method: 'post',
    path: '/v1/room-requests',
    summary: 'J02: request free, listed slots; auto-approved only when the centre switched it on',
    tag: 'rooms',
    rules: ['MKT-HAL-02', 'MKT-HAL-05'],
    auth: 'user',
    idempotent: true,
    body: m.RoomRequestBody,
    response: m.RoomRequest,
    status: 201,
    errors: [
      { status: 409, code: 'slot_taken' },
      { status: 409, code: 'centre_not_verified' },
      { status: 409, code: 'hall_not_listed' },
    ],
  }),
  roomRequests: def({
    name: 'listRoomRequests',
    method: 'get',
    path: '/v1/room-requests',
    summary: 'scope=mine: my requests (J03); centreId: the centre pipeline (C06)',
    tag: 'rooms',
    rules: ['MKT-HAL-03', 'MKT-HAL-04'],
    auth: 'user',
    query: m.RoomRequestsQuery,
    response: m.RoomRequestList,
  }),
  stageRequest: def({
    name: 'moveRoomRequest',
    method: 'post',
    path: '/v1/room-requests/{id}/stage',
    summary: 'C06: forward only, phone call then meeting',
    tag: 'rooms',
    rules: ['MKT-HAL-04'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    body: m.StageBody,
    response: m.RoomRequest,
    errors: [
      { status: 409, code: 'stage_backwards' },
      { status: 409, code: 'request_closed' },
    ],
  }),
  approveRequest: def({
    name: 'approveRoomRequest',
    method: 'post',
    path: '/v1/room-requests/{id}/approve',
    summary: 'C06: approval books the slot (CF-46); a taken slot is refused',
    tag: 'rooms',
    rules: ['MKT-HAL-04', 'CF-46'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    body: m.EmptyBody,
    response: m.RoomRequest,
    errors: [
      { status: 409, code: 'slot_taken' },
      { status: 409, code: 'centre_not_verified' },
    ],
  }),
  declineRequest: def({
    name: 'declineRoomRequest',
    method: 'post',
    path: '/v1/room-requests/{id}/decline',
    summary: 'C06: decline with a reason',
    tag: 'rooms',
    rules: ['MKT-HAL-04'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    body: m.DeclineBody,
    response: m.RoomRequest,
    errors: [{ status: 422, code: 'reason_required' }],
  }),
  withdrawRequest: def({
    name: 'withdrawRoomRequest',
    method: 'post',
    path: '/v1/room-requests/{id}/withdraw',
    summary: 'J03: the teacher withdraws an undecided request',
    tag: 'rooms',
    rules: ['MKT-HAL-03'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    body: m.EmptyBody,
    response: m.RoomRequest,
  }),
  myBookings: def({
    name: 'listMyBookings',
    method: 'get',
    path: '/v1/room-bookings',
    summary: 'My bookings (scope=mine): a group can be opened in a booked slot (J05)',
    tag: 'rooms',
    rules: ['MKT-GRP-01'],
    auth: 'user',
    query: m.BookingsQuery,
    response: m.TeacherBookingList,
  }),

  // ── Teacher profile and groups (J04, J05) ────────────────────────────────────
  teacherSelf: def({
    name: 'getTeacherSelf',
    method: 'get',
    path: '/v1/teachers/me',
    summary: 'Own profile, verification, settings and what the teacher teaches',
    tag: 'teachers',
    rules: ['MKT-TCH-01'],
    auth: 'user',
    response: m.TeacherSelf,
  }),
  patchTeacherSelf: def({
    name: 'patchTeacherSelf',
    method: 'patch',
    path: '/v1/teachers/me',
    summary:
      'Profile, subjects, availability, settings; name, a subject and an accepted invite make it public',
    tag: 'teachers',
    rules: ['MKT-TCH-01', 'OD-08'],
    auth: 'user',
    idempotent: true,
    body: m.TeacherSelfPatch,
    response: m.TeacherSelf,
  }),
  teacherGroups: def({
    name: 'listTeacherGroups',
    method: 'get',
    path: '/v1/teachers/me/groups',
    summary: 'My groups with seats filled and the next session (follow-up parts arrive in R3)',
    tag: 'teachers',
    rules: ['CF-30'],
    auth: 'user',
    response: m.TeacherGroupList,
  }),
  createGroup: def({
    name: 'createGroup',
    method: 'post',
    path: '/v1/groups',
    summary: 'J05: a group in a booked slot; seats never above the hall; sessions from the slot',
    tag: 'groups',
    rules: ['MKT-GRP-01', 'CF-05'],
    auth: 'user',
    idempotent: true,
    body: m.NewGroupBody,
    response: m.Created,
    status: 201,
    errors: [
      { status: 422, code: 'seat_cap_above_hall' },
      { status: 409, code: 'booking_has_group' },
    ],
  }),
  patchGroup: def({
    name: 'patchGroup',
    method: 'patch',
    path: '/v1/groups/{id}',
    summary: 'J05: fees, seats (at most the hall, at least the seats taken), monthly plan',
    tag: 'groups',
    rules: ['MKT-GRP-02'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    body: m.GroupPatch,
    response: m.Ok,
    errors: [
      { status: 422, code: 'seat_cap_above_hall' },
      { status: 409, code: 'seat_cap_below_filled' },
    ],
  }),
  group: def({
    name: 'getGroup',
    method: 'get',
    path: '/v1/groups/{id}',
    summary: 'A published group with seats left per upcoming session',
    tag: 'groups',
    rules: ['MKT-ENR-01'],
    auth: 'public',
    params: m.IdParams,
    response: m.GroupSummary,
  }),

  // ── Discovery (P02–P05) ──────────────────────────────────────────────────────
  searchCentres: def({
    name: 'searchCentres',
    method: 'get',
    path: '/v1/search/centres',
    summary: 'P02/P03: verified centres with matching groups within the radius (default 5 km)',
    tag: 'search',
    rules: ['MKT-DSC-01', 'MKT-DSC-02'],
    auth: 'public',
    query: m.SearchQuery,
    response: m.SearchCentresResult,
  }),
  searchTeachers: def({
    name: 'searchTeachers',
    method: 'get',
    path: '/v1/search/teachers',
    summary: 'P03: active teachers with matching groups within the radius',
    tag: 'search',
    rules: ['MKT-DSC-02'],
    auth: 'public',
    query: m.SearchQuery,
    response: m.TeacherCardPage,
  }),
  centreBySlug: def({
    name: 'getCentreBySlug',
    method: 'get',
    path: '/v1/centres/by-slug/{slug}',
    summary: 'P04: a verified centre, its teachers and the groups for the child',
    tag: 'search',
    rules: ['MKT-DSC-04', 'CF-44'],
    auth: 'public',
    params: m.SlugParams,
    query: m.CentreBySlugQuery,
    response: m.CentreProfileWithGroups,
  }),
  teacherBySlug: def({
    name: 'getTeacherBySlug',
    method: 'get',
    path: '/v1/teachers/by-slug/{slug}',
    summary: 'P05: an active teacher and their groups',
    tag: 'search',
    rules: ['MKT-DSC-05'],
    auth: 'public',
    params: m.SlugParams,
    response: m.TeacherProfile,
  }),
  // ── Enrolment and payment (07 §2, docs/08 §4) ─────────────────────────────────
  createEnrolment: def({
    name: 'createEnrolment',
    method: 'post',
    path: '/v1/enrolments',
    summary: 'Hold a seat in every covered session (10 min; Fawry 24 h after checkout)',
    tag: 'enrolment',
    rules: ['MKT-ENR-02', 'BR-ENR-01', 'BR-ENR-02', 'BR-ENR-08', 'BR-ENR-13'],
    auth: 'user',
    idempotent: true,
    body: $.CreateEnrolmentBody,
    response: $.Enrolment,
    status: 201,
    errors: [
      { status: 409, code: 'seat_unavailable' },
      { status: 409, code: 'already_enrolled' },
      { status: 422, code: 'plan_not_offered' },
    ],
  }),
  checkout: def({
    name: 'checkoutEnrolment',
    method: 'post',
    path: '/v1/enrolments/{id}/checkout',
    summary: 'The provider hosted page, or a Fawry reference; again after a failed attempt',
    tag: 'enrolment',
    rules: ['MKT-ENR-03', 'MKT-ENR-04', 'MKT-ENR-05', 'MKT-ENR-12', 'BR-PMT-02', 'BR-MNY-06'],
    auth: 'user',
    idempotent: true,
    money: true,
    params: m.IdParams,
    body: $.CheckoutBody,
    response: $.CheckoutResult,
    errors: [
      { status: 409, code: 'hold_expired' },
      { status: 422, code: 'method_not_allowed' },
      { status: 502, code: 'provider_unavailable' },
    ],
  }),
  enrolment: def({
    name: 'getEnrolment',
    method: 'get',
    path: '/v1/enrolments/{id}',
    summary: 'One enrolment: one of the 8 states, never cached',
    tag: 'enrolment',
    rules: ['MKT-ENR-06', 'BR-MNY-10'],
    auth: 'user',
    params: m.IdParams,
    response: $.Enrolment,
  }),
  myEnrolments: def({
    name: 'listMyEnrolments',
    method: 'get',
    path: '/v1/me/enrolments',
    summary: 'My children enrolments (P09)',
    tag: 'enrolment',
    rules: ['MKT-ENR-07'],
    auth: 'user',
    response: $.EnrolmentPage,
  }),
  cancelEnrolment: def({
    name: 'cancelEnrolment',
    method: 'post',
    path: '/v1/enrolments/{id}/cancel',
    summary: 'Cancel before paying, or before the first session (refund requested)',
    tag: 'enrolment',
    rules: ['MKT-ENR-08', 'BR-REF-02'],
    auth: 'user',
    idempotent: true,
    money: true,
    params: m.IdParams,
    body: m.EmptyBody,
    response: $.Enrolment,
    errors: [{ status: 409, code: 'after_first_session' }],
  }),
  cancelPlan: def({
    name: 'cancelPlan',
    method: 'post',
    path: '/v1/enrolments/{id}/plan/cancel',
    summary: 'Stop the next renewal; the paid month stays',
    tag: 'enrolment',
    rules: ['BR-PMT-05'],
    auth: 'user',
    idempotent: true,
    money: true,
    params: m.IdParams,
    body: m.EmptyBody,
    response: $.Enrolment,
  }),
  refundRequest: def({
    name: 'requestRefund',
    method: 'post',
    path: '/v1/enrolments/{id}/refund-requests',
    summary: 'After the first session: a refund review by Link ops (dispute)',
    tag: 'enrolment',
    rules: ['BR-REF-03'],
    auth: 'user',
    idempotent: true,
    money: true,
    params: m.IdParams,
    body: $.RefundRequestBody,
    response: $.Enrolment,
  }),
  teacherEnrolments: def({
    name: 'listTeacherEnrolments',
    method: 'get',
    path: '/v1/teachers/me/enrolments',
    summary: 'J06: paid enrolments in my groups',
    tag: 'enrolment',
    rules: ['MKT-ENR-10', 'BR-ENR-07'],
    auth: 'user',
    response: $.TeacherEnrolmentList,
  }),
  acceptEnrolment: def({
    name: 'acceptEnrolment',
    method: 'post',
    path: '/v1/enrolments/{id}/accept',
    summary: 'J06 with reviewEachEnrolment on: accept',
    tag: 'enrolment',
    rules: ['MKT-ENR-10', 'OD-08'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    body: m.EmptyBody,
    response: $.TeacherEnrolment.nullable(),
    errors: [{ status: 409, code: 'not_awaiting_teacher' }],
  }),
  declineEnrolment: def({
    name: 'declineEnrolment',
    method: 'post',
    path: '/v1/enrolments/{id}/decline',
    summary: 'J06 with reviewEachEnrolment on: decline, with an automatic full refund',
    tag: 'enrolment',
    rules: ['MKT-ENR-10', 'OD-08', 'BR-REF-07'],
    auth: 'user',
    idempotent: true,
    money: true,
    params: m.IdParams,
    body: m.EmptyBody,
    response: $.TeacherEnrolment.nullable(),
    errors: [{ status: 409, code: 'not_awaiting_teacher' }],
  }),
  joinWaitlist: def({
    name: 'joinWaitlist',
    method: 'post',
    path: '/v1/groups/{id}/waitlist',
    summary: 'Join the waitlist of a full group (free)',
    tag: 'enrolment',
    rules: ['MKT-ENR-09', 'BR-ENR-10'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    body: $.WaitlistBody,
    response: $.WaitlistEntry,
    status: 201,
  }),
  acceptWaitlistOffer: def({
    name: 'acceptWaitlistOffer',
    method: 'post',
    path: '/v1/waitlist/{id}/accept',
    summary: 'Accept a live offer: the offered seat becomes a hold, and the checkout opens',
    tag: 'enrolment',
    rules: ['MKT-ENR-09', 'BR-ENR-10'],
    auth: 'user',
    idempotent: true,
    money: true,
    params: m.IdParams,
    body: $.WaitlistAcceptBody,
    response: $.CheckoutResult,
    errors: [{ status: 409, code: 'offer_expired' }],
  }),
  leaveWaitlist: def({
    name: 'leaveWaitlist',
    method: 'delete',
    path: '/v1/waitlist/{id}',
    summary: 'Leave the waitlist; an open offer goes to the next family',
    tag: 'enrolment',
    rules: ['MKT-ENR-09'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    response: null,
  }),
  paymentWebhook: def({
    name: 'paymentWebhook',
    method: 'post',
    path: '/v1/webhooks/payments/{provider}',
    summary: 'Provider to Link: signature verified first, deduplicated on the provider event ID',
    tag: 'webhooks',
    rules: ['BR-MNY-12', 'BR-MNY-04', 'INV-01'],
    auth: 'public',
    params: $.ProviderParams,
    response: $.WebhookAck,
    errors: [{ status: 401, code: 'invalid_signature' }],
  }),

  // ── Money statements (07 §2) ──────────────────────────────────────────────────
  earnings: def({
    name: 'getTeacherEarnings',
    method: 'get',
    path: '/v1/teachers/me/earnings',
    summary: 'J07 from the ledger: parents paid, Link commission, rent per hall, next payout',
    tag: 'money',
    rules: ['MKT-LED-07', 'BR-FEE-07', 'BR-OUT-07', 'OD-04'],
    auth: 'user',
    response: $.Earnings,
  }),
  rentIncome: def({
    name: 'getRentIncome',
    method: 'get',
    path: '/v1/centres/{id}/rent-income',
    summary: 'C07 from the ledger and rent invoices: rent, Link fee, net (owner only)',
    tag: 'money',
    rules: ['MKT-LED-08', 'BR-RNT-07', 'BR-FEE-07'],
    auth: 'user',
    params: s.CentreParams,
    response: $.RentIncome,
  }),

  // ── Reviews (07 §2) ───────────────────────────────────────────────────────────
  createReview: def({
    name: 'createReview',
    method: 'post',
    path: '/v1/reviews',
    summary: 'A verified parent reviews, after the first session, once per target and term',
    tag: 'reviews',
    rules: ['MKT-REV-01', 'BR-REV-01', 'BR-REV-02', 'BR-REV-04', 'CF-27'],
    auth: 'user',
    idempotent: true,
    body: $.CreateReviewBody,
    response: $.ReviewCreated,
    status: 201,
    errors: [
      { status: 403, code: 'not_verified_parent' },
      { status: 409, code: 'already_reviewed' },
    ],
  }),
  reviewsReceived: def({
    name: 'listReviewsReceived',
    method: 'get',
    path: '/v1/me/reviews-received',
    summary:
      'C04 tabs: visibility=public, visibility=private, status=reported; owners and staff pass centreId',
    tag: 'reviews',
    rules: ['MKT-REV-03'],
    auth: 'user',
    query: $.ReviewsReceivedQuery,
    response: $.ReviewsReceived,
  }),
  replyReview: def({
    name: 'replyReview',
    method: 'post',
    path: '/v1/reviews/{id}/reply',
    summary: 'The target replies publicly (never edits, hides or deletes)',
    tag: 'reviews',
    rules: ['MKT-REV-03', 'BR-REV-06'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    body: $.ReplyBody,
    response: m.Ok,
    errors: [
      { status: 409, code: 'private_feedback' },
      { status: 409, code: 'already_replied' },
    ],
  }),
  reportReview: def({
    name: 'reportReview',
    method: 'post',
    path: '/v1/reviews/{id}/report',
    summary: 'The target reports a review to Link ops',
    tag: 'reviews',
    rules: ['MKT-REV-03', 'BR-REV-04', 'BR-REV-06'],
    auth: 'user',
    idempotent: true,
    params: m.IdParams,
    body: $.ReportBody,
    response: m.Ok,
  }),

  // ── Follow-up, the paid extra (R3, 07 §2b–§2d) ───────────────────────────────
  ...followupRoutes,

  // ── Ops console and data-subject requests (S2, 07 "Ops") ─────────────────────
  ...opsRoutes,
} satisfies Record<string, RouteDef>;

export type RouteName = keyof typeof routes;
export const allRoutes: RouteDef[] = Object.values(routes);
