import { z } from 'zod';

/**
 * The API contract (07). Every request and response shape is a Zod schema here; `.meta({id})`
 * names the OpenAPI component, and those names are the TypeScript names in `@link/api-client`
 * (generated by `pnpm openapi:generate`). Change a shape here, never in the client by hand.
 */
const named = <T extends z.ZodType>(id: string, s: T, description?: string) =>
  s.meta({ id, ...(description ? { description } : {}) });

export const Uuid = z.uuid();
export const Lang = z.enum(['ar', 'en']);

// ── Errors and paging (07 §1) ──────────────────────────────────────────────────
export const ProblemDetails = named(
  'ProblemDetails',
  z
    .object({
      type: z.string(),
      title: z.string(),
      status: z.number().int(),
      detail: z.string().optional(),
      code: z.string(),
      requestId: z.string().optional(),
      errors: z
        .array(z.object({ field: z.string(), code: z.string() }).catchall(z.unknown()))
        .optional(),
    })
    .catchall(z.unknown()),
  'RFC 9457 problem. Clients switch on `code`.',
);

// ── Auth and account (MKT-ACC) ─────────────────────────────────────────────────
export const Role = named('Role', z.enum(['parent', 'teacher', 'centre_owner', 'centre_staff']));

export const Me = named(
  'Me',
  z.object({
    id: z.string(),
    name: z.string().nullable(),
    language: Lang,
    roles: z.array(Role),
    centreIds: z.array(z.string()).optional().describe('Centres where the user is owner or staff'),
    teacherId: z.string().nullable().optional(),
  }),
);

export const OtpRequestBody = named(
  'OtpRequestBody',
  z.object({ phone: z.string().min(1).max(32) }),
);
export const OtpRequestResult = named(
  'OtpRequestResult',
  z.object({
    resendAfterSeconds: z.number().int().describe('Seconds until "Resend" is allowed (60)'),
    expiresInSeconds: z.number().int().describe('Code lifetime (300)'),
  }),
);
export const OtpVerifyBody = named(
  'OtpVerifyBody',
  z.object({ phone: z.string().min(1).max(32), code: z.string().min(1).max(12) }),
);
export const OtpVerifyResult = named(
  'OtpVerifyResult',
  z.object({
    accessToken: z.string().optional().describe('Teacher app only; the web gets cookies'),
    refreshToken: z.string().optional(),
    user: Me,
    isNewUser: z
      .boolean()
      .describe('True when the phone had no account: the client then adds the chosen role'),
  }),
);
export const RefreshBody = named(
  'RefreshBody',
  z.object({
    refreshToken: z.string().optional().describe('Teacher app; the web sends the cookie'),
  }),
);
export const TokenPair = named(
  'TokenPair',
  z.object({ accessToken: z.string().optional(), refreshToken: z.string().optional() }),
);
export const UpdateMeBody = named(
  'UpdateMeBody',
  z
    .object({ name: z.string().trim().min(1).max(80).optional(), language: Lang.optional() })
    .refine((b) => b.name !== undefined || b.language !== undefined, 'name or language'),
);
export const AddRoleBody = named(
  'AddRoleBody',
  z.object({ role: z.enum(['parent', 'teacher', 'centre_owner']) }),
);

export const ConsentKind = named(
  'ConsentKind',
  z.enum([
    'terms',
    'privacy',
    'child_data_processing',
    'share_phone_with_teacher',
    'whatsapp_updates',
    'sms_updates',
    'focus_plans',
    'ai_training_use',
  ]),
);
export const PutConsentBody = named(
  'PutConsentBody',
  z.object({
    kind: ConsentKind,
    granted: z.boolean(),
    version: z.string().min(1).max(40).describe('Text version the person saw'),
    studentId: z.string().optional(),
  }),
);
export const ConsentState = named(
  'ConsentState',
  z.object({
    kind: ConsentKind,
    studentId: z.string().nullable(),
    granted: z.boolean(),
    version: z.string(),
    at: z.string(),
  }),
);
export const ConsentList = named('ConsentList', z.object({ data: z.array(ConsentState) }));

// ── Reference data ─────────────────────────────────────────────────────────────
export const CurriculumCode = named(
  'Curriculum',
  z.enum(['NATIONAL', 'IGCSE', 'AMERICAN', 'NILE']),
);
export const CurriculumRef = named(
  'CurriculumRef',
  z.object({ id: z.string(), code: CurriculumCode, name: z.string() }),
);
export const SchoolYearRef = named(
  'SchoolYearRef',
  z.object({
    id: z.string(),
    code: z.string(),
    name: z.string(),
    shortName: z.string().describe('Short form for chips: "Sec 2" (07 §2a P-4)'),
  }),
);
export const SubjectRef = named(
  'SubjectRef',
  z.object({ id: z.string(), code: z.string(), name: z.string() }),
);
export const CurriculumWithYears = named(
  'CurriculumWithYears',
  CurriculumRef.extend({ schoolYears: z.array(SchoolYearRef) }),
);
export const CurriculumList = z.array(CurriculumWithYears);
export const SubjectList = z.array(SubjectRef);
export const SubjectsQuery = z.object({
  curriculumId: z.string().optional(),
  schoolYearId: z.string().optional(),
});

// ── Children (MKT-ACC-05) ──────────────────────────────────────────────────────
export const Child = named(
  'Child',
  z.object({
    id: z.string(),
    displayName: z.string(),
    curriculum: CurriculumRef,
    schoolYear: SchoolYearRef,
  }),
);
export const ChildPage = named(
  'ChildPage',
  z.object({ data: z.array(Child), nextCursor: z.string().nullable() }),
);
export const NewChildBody = named(
  'NewChildBody',
  z.object({
    displayName: z.string().trim().min(1).max(80),
    curriculumId: Uuid,
    schoolYearId: Uuid,
  }),
);

// ── Centres: C01 join request, staff (MKT-CEN-01, MKT-ACC-06) ─────────────────
export const CentreApplicationBody = named(
  'CentreApplicationBody',
  z.object({
    centreName: z.string().trim().min(1).max(120),
    governorate: z.string().trim().min(1).max(60),
    area: z.string().trim().min(1).max(60),
    address: z.string().trim().min(1).max(200),
    subjects: z.array(z.string().max(40)).max(20),
    hallRange: z.enum(['1-3', '4-8', '9+']),
    ownerName: z.string().trim().min(1).max(80),
    phone: z.string().min(1).max(32),
    consent: z.boolean(),
  }),
);
export const CentreApplicationResult = named(
  'CentreApplicationResult',
  z.object({ id: z.string() }),
);

export const StaffPermission = named(
  'StaffPermission',
  z.enum(['bookings.manage', 'reviews.reply']),
);
export const PersonRef = named('PersonRef', z.object({ id: z.string(), displayName: z.string() }));
export const StaffMember = named(
  'StaffMember',
  z.object({
    user: PersonRef,
    role: z.enum(['owner', 'reception', 'teacher']),
    scope: z.string(),
    permissions: z.array(StaffPermission).describe('Marketplace permissions (A16, MKT-ACC-06 AC1)'),
    lastActiveAt: z.string().nullable(),
    status: z.enum(['active', 'invite_pending', 'removed']),
  }),
);
export const StaffList = z.array(StaffMember);
export const InviteStaffBody = named(
  'InviteStaffBody',
  z.object({
    phone: z.string().min(1).max(32),
    role: z.enum(['reception', 'teacher']),
    permissions: z.array(StaffPermission).optional(),
  }),
);

// ── Feature flags and paid extras (OD-58) ──────────────────────────────────────
export const CentreFeatures = named(
  'CentreFeatures',
  z.object({ followupExtra: z.boolean().describe('The Follow-up paid extra is on') }),
);
export const FeatureFlags = named(
  'FeatureFlags',
  z.object({
    flags: z
      .record(z.string(), z.boolean())
      .describe('Global flags merged with the caller’s centre and teacher scopes'),
  }),
);

// ── Path parameters ────────────────────────────────────────────────────────────
export const CentreParams = z.object({ id: Uuid });
