/**
 * Every screen of the web app and the teacher app: the route manifest that the dev index
 * (`/{lang}/dev`, demo only) lists and the route crawlers visit (apps/web/e2e-demo/routes.spec.ts,
 * apps/pilot/e2e/routes.spec.ts). The crawlers also check that every page file has an entry here.
 *
 * IDs and Figma nodes: docs/11 §7. Status: docs/frontend/screen-log.md. Names are the Figma frame
 * names (English, as in the inventory): this list is a developer tool, not product copy.
 */

export type ScreenApp = 'web' | 'teacher';
export type ScreenRole = 'anyone' | 'parent' | 'owner' | 'reception' | 'teacher';
export type ScreenMode = 'demo' | 'pilot';
export type ScreenStatus = 'built' | 'placeholder' | 'needs design review' | 'dev only';

export interface Screen {
  /** Screen ID from docs/11 §7 (or a short label for screens with no Figma frame). */
  id: string;
  name: string;
  app: ScreenApp;
  /**
   * Path after `/{lang}` (web) or from the app root (teacher), with any query the screen needs.
   * `{param}` = a sample id.
   */
  path: string;
  roles: ScreenRole[];
  modes: ScreenMode[];
  status: ScreenStatus;
  /** Figma node id (`5:2`), when the screen has a frame. */
  figma?: string;
  /** Only reached inside a flow (needs state the URL alone does not carry). */
  flow?: string;
  /** Shown with this demo flag on: Phase 2 (follow-up) or the marketplace (Phase 1). */
  flag?: 'phase2' | 'marketplace';
}

const STAFF: ScreenRole[] = ['owner', 'reception'];
const BOTH: ScreenMode[] = ['demo', 'pilot'];
const DEMO: ScreenMode[] = ['demo'];

export const SCREENS: Screen[] = [
  // Website (landing page, Figma 68:616; Stage 1 of the launch)
  {
    id: 'W00',
    name: 'Landing page',
    app: 'web',
    path: '/',
    roles: ['anyone'],
    modes: DEMO,
    status: 'built',
    figma: '68:616',
  },
  {
    id: 'W-TRY',
    name: 'Try Link: choose a role (Parent · Teacher · Centre owner)',
    app: 'web',
    path: '/try',
    roles: ['anyone'],
    modes: DEMO,
    status: 'built',
  },
  {
    id: 'W-PILOT',
    name: 'Request a free pilot (path B)',
    app: 'web',
    path: '/pilot',
    roles: ['anyone'],
    modes: DEMO,
    status: 'built',
  },
  {
    id: 'W-SIGNIN',
    name: 'Sign in (pilot centres)',
    app: 'web',
    path: '/sign-in',
    roles: ['anyone'],
    modes: DEMO,
    status: 'built',
  },
  // Public pages
  {
    id: 'P01',
    name: 'Welcome & sign up',
    app: 'web',
    path: '/welcome',
    roles: ['anyone'],
    modes: DEMO,
    status: 'built',
    figma: '39:260',
  },
  {
    id: 'P01-T',
    name: 'Teacher: continue in the app',
    app: 'web',
    path: '/welcome/teacher',
    roles: ['anyone'],
    modes: DEMO,
    status: 'needs design review',
  },
  {
    id: 'C01',
    name: 'Add my centre to Link',
    app: 'web',
    path: '/add-your-centre',
    roles: ['anyone'],
    modes: DEMO,
    status: 'built',
    figma: '45:273',
  },

  // Parent PWA
  {
    id: 'P02',
    name: 'Search home',
    app: 'web',
    path: '/search',
    roles: ['parent'],
    modes: DEMO,
    status: 'built',
    figma: '39:334',
    flag: 'marketplace',
  },
  {
    id: 'P03',
    name: 'Map & results',
    app: 'web',
    path: '/search/results',
    roles: ['parent'],
    modes: DEMO,
    status: 'built',
    figma: '40:261',
    flag: 'marketplace',
  },
  {
    id: 'P04',
    name: 'Centre profile',
    app: 'web',
    path: '/centres/{centreSlug}',
    roles: ['parent'],
    modes: DEMO,
    status: 'built',
    figma: '40:374',
    flag: 'marketplace',
  },
  {
    id: 'P05',
    name: 'Teacher profile',
    app: 'web',
    path: '/teachers/{teacherSlug}',
    roles: ['parent'],
    modes: DEMO,
    status: 'built',
    figma: '42:262',
    flag: 'marketplace',
  },
  {
    id: 'P06',
    name: 'Choose a group & start date',
    app: 'web',
    path: '/teachers/{teacherSlug}/reserve',
    roles: ['parent'],
    modes: DEMO,
    status: 'built',
    figma: '42:357',
    flag: 'marketplace',
  },
  {
    id: 'P07',
    name: 'Reserve & pay',
    app: 'web',
    path: '/reserve/{enrolmentId}',
    roles: ['parent'],
    modes: DEMO,
    status: 'built',
    figma: '43:264',
    flag: 'marketplace',
  },
  {
    id: 'P08',
    name: 'Place reserved',
    app: 'web',
    path: '/reserve/{enrolmentId}/done',
    roles: ['parent'],
    modes: DEMO,
    status: 'built',
    figma: '43:372',
    flag: 'marketplace',
  },
  {
    id: 'P09',
    name: 'My children',
    app: 'web',
    path: '/children',
    roles: ['parent'],
    modes: DEMO,
    status: 'built',
    figma: '44:268',
  },
  {
    id: 'P10',
    name: 'Leave feedback',
    app: 'web',
    path: '/enrolments/{enrolmentId}/feedback',
    roles: ['parent'],
    modes: DEMO,
    status: 'built',
    figma: '44:362',
  },
  {
    id: 'P-ACC',
    name: 'Account',
    app: 'web',
    path: '/account',
    roles: ['parent'],
    modes: DEMO,
    status: 'needs design review',
  },
  {
    id: 'P-PAY',
    name: 'Mock payment provider page',
    app: 'web',
    path: '/mock-checkout/{paymentId}',
    roles: ['parent'],
    modes: DEMO,
    status: 'dev only',
    flow: 'P07 → Pay',
  },

  // Owner web (centre workspace)
  {
    id: 'A18',
    name: 'Owner sign-in by phone code (name + PIN in the pilot)',
    app: 'web',
    path: '/centre',
    roles: ['anyone'],
    modes: BOTH,
    status: 'built',
    figma: '31:233',
  },
  {
    id: 'A01',
    name: 'Today',
    app: 'web',
    path: '/centre/{centreId}/today',
    roles: STAFF,
    modes: BOTH,
    status: 'built',
    figma: '5:2',
    flag: 'phase2',
  },
  {
    id: 'A02',
    name: 'Follow-ups list',
    app: 'web',
    path: '/centre/{centreId}/follow-ups',
    roles: STAFF,
    modes: BOTH,
    status: 'built',
    figma: '5:83',
    flag: 'phase2',
  },
  {
    id: 'A03',
    name: 'Follow-up case',
    app: 'web',
    path: '/centre/{centreId}/follow-ups/{caseId}',
    roles: STAFF,
    modes: BOTH,
    status: 'built',
    figma: '5:153',
    flag: 'phase2',
  },
  {
    id: 'V06',
    name: 'Parent replied — next step',
    app: 'web',
    path: '/centre/{centreId}/follow-ups/{caseId}/reply?message={messageId}',
    roles: STAFF,
    modes: DEMO,
    status: 'built',
    figma: '36:284',
    flag: 'phase2',
  },
  {
    id: 'A08',
    name: 'Record outcome',
    app: 'web',
    path: '/centre/{centreId}/follow-ups/{caseId}/outcome',
    roles: STAFF,
    modes: BOTH,
    status: 'built',
    figma: '7:47',
    flag: 'phase2',
  },
  {
    id: 'A10',
    name: 'Outcome recorded',
    app: 'web',
    path: '/centre/{centreId}/follow-ups/{caseId}/outcome/done',
    roles: STAFF,
    modes: BOTH,
    status: 'built',
    figma: '7:143',
    flag: 'phase2',
  },
  {
    id: 'A06',
    name: 'Review parent message (A09 once approved)',
    app: 'web',
    path: '/centre/{centreId}/messages/{messageId}',
    roles: STAFF,
    modes: BOTH,
    status: 'built',
    figma: '5:367',
    flag: 'phase2',
  },
  {
    id: 'A13',
    name: 'Students',
    app: 'web',
    path: '/centre/{centreId}/students',
    roles: STAFF,
    modes: BOTH,
    status: 'built',
    figma: '25:168',
    flag: 'phase2',
  },
  {
    id: 'A04',
    name: 'Student profile',
    app: 'web',
    path: '/centre/{centreId}/students/{studentId}',
    roles: STAFF,
    modes: BOTH,
    status: 'built',
    figma: '5:229',
    flag: 'phase2',
  },
  {
    id: 'A05',
    name: 'Sessions',
    app: 'web',
    path: '/centre/{centreId}/sessions',
    roles: STAFF,
    modes: BOTH,
    status: 'built',
    figma: '5:302',
    flag: 'phase2',
  },
  {
    id: 'A14',
    name: 'Session record detail',
    app: 'web',
    path: '/centre/{centreId}/sessions/{recordId}',
    roles: STAFF,
    modes: BOTH,
    status: 'built',
    figma: '26:178',
    flag: 'phase2',
  },
  {
    id: 'A11',
    name: 'Parent communication',
    app: 'web',
    path: '/centre/{centreId}/communication',
    roles: STAFF,
    modes: BOTH,
    status: 'built',
    figma: '15:79',
    flag: 'phase2',
  },
  {
    id: 'A07',
    name: 'Rules & settings',
    app: 'web',
    path: '/centre/{centreId}/rules',
    roles: STAFF,
    modes: BOTH,
    status: 'built',
    figma: '5:423',
    flag: 'phase2',
  },
  {
    id: 'A17',
    name: 'Activity history',
    app: 'web',
    path: '/centre/{centreId}/activity',
    roles: STAFF,
    modes: BOTH,
    status: 'built',
    figma: '30:230',
    flag: 'phase2',
  },
  {
    id: 'A16',
    name: 'Staff & access (pilot: people, PINs, voice per teacher)',
    app: 'web',
    path: '/centre/{centreId}/staff',
    roles: STAFF,
    modes: BOTH,
    status: 'built',
    figma: '29:215',
  },
  {
    id: 'C02',
    name: 'Public profile editor',
    app: 'web',
    path: '/centre/{centreId}/profile',
    roles: STAFF,
    modes: DEMO,
    status: 'built',
    figma: '46:274',
    flag: 'marketplace',
  },
  {
    id: 'C03',
    name: 'Room schedule',
    app: 'web',
    path: '/centre/{centreId}/schedule',
    roles: STAFF,
    modes: DEMO,
    status: 'built',
    figma: '56:375',
    flag: 'marketplace',
  },
  {
    id: 'C04',
    name: 'Reviews & private feedback',
    app: 'web',
    path: '/centre/{centreId}/reviews',
    roles: STAFF,
    modes: DEMO,
    status: 'built',
    figma: '48:295',
    flag: 'marketplace',
  },
  {
    id: 'C05',
    name: 'Rooms & rent',
    app: 'web',
    path: '/centre/{centreId}/rooms',
    roles: STAFF,
    modes: DEMO,
    status: 'built',
    figma: '57:364',
    flag: 'marketplace',
  },
  {
    id: 'C06',
    name: 'Room requests from teachers',
    app: 'web',
    path: '/centre/{centreId}/requests',
    roles: STAFF,
    modes: DEMO,
    status: 'built',
    figma: '49:307',
    flag: 'marketplace',
  },
  {
    id: 'C07',
    name: 'Rent income from teachers',
    app: 'web',
    path: '/centre/{centreId}/rent-income',
    roles: STAFF,
    modes: DEMO,
    status: 'built',
    figma: '58:358',
    flag: 'marketplace',
  },
  {
    id: 'C-EXTRA',
    name: "Follow-up, a paid extra: what's included (OD-58)",
    app: 'web',
    path: '/centre/{centreId}/followup-extra',
    roles: STAFF,
    modes: DEMO,
    status: 'built',
    flag: 'marketplace',
  },

  // Developer
  {
    id: 'DEV',
    name: 'Dev route index (this page)',
    app: 'web',
    path: '/dev',
    roles: ['anyone'],
    modes: DEMO,
    status: 'dev only',
  },

  // Teacher app (Expo; Expo web on :8081 in the demo, :8444 / 9444 in the pilot)
  {
    id: 'T14',
    name: 'Sign in by phone code (name + PIN in the pilot)',
    app: 'teacher',
    path: '/sign-in',
    roles: ['anyone'],
    modes: BOTH,
    status: 'built',
    figma: '23:237',
  },
  {
    id: 'T01',
    name: 'Today (the Follow-up tab)',
    app: 'teacher',
    path: '/today',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '7:183',
    flag: 'phase2',
  },
  {
    id: 'T09',
    name: 'My groups & fees (T09 + J05, CF-30)',
    app: 'teacher',
    path: '/groups',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '18:146',
  },
  {
    id: 'T13-tab',
    name: 'Records (tab)',
    app: 'teacher',
    path: '/records',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '23:156',
    flag: 'phase2',
  },
  {
    id: 'J01',
    name: 'Find a room to rent',
    app: 'teacher',
    path: '/rooms',
    roles: ['teacher'],
    modes: DEMO,
    status: 'built',
    figma: '59:358',
    flag: 'marketplace',
  },
  {
    id: 'J02',
    name: 'Request a slot',
    app: 'teacher',
    path: '/room/{hallId}',
    roles: ['teacher'],
    modes: DEMO,
    status: 'built',
    figma: '59:462',
    flag: 'marketplace',
  },
  {
    id: 'J03',
    name: 'My room requests',
    app: 'teacher',
    path: '/room-requests',
    roles: ['teacher'],
    modes: DEMO,
    status: 'built',
    figma: '51:341',
    flag: 'marketplace',
  },
  {
    id: 'J04',
    name: 'My profile',
    app: 'teacher',
    path: '/profile',
    roles: ['teacher'],
    modes: DEMO,
    status: 'built',
    figma: '51:447',
    flag: 'marketplace',
  },
  {
    id: 'J06',
    name: 'New enrolments',
    app: 'teacher',
    path: '/enrolments',
    roles: ['teacher'],
    modes: DEMO,
    status: 'built',
    figma: '60:452',
    flag: 'marketplace',
  },
  {
    id: 'J07',
    name: 'Earnings',
    app: 'teacher',
    path: '/earnings',
    roles: ['teacher'],
    modes: DEMO,
    status: 'built',
    figma: '61:373',
    flag: 'marketplace',
  },
  {
    id: 'T10',
    name: 'Group roster',
    app: 'teacher',
    path: '/group/{groupId}',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '19:152',
    flag: 'phase2',
  },
  {
    id: 'T13',
    name: 'Records history',
    app: 'teacher',
    path: '/group/{groupId}/history',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '23:156',
    flag: 'phase2',
  },
  {
    id: 'T02',
    name: 'Confirm attendance',
    app: 'teacher',
    path: '/record/{recordId}/attendance',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '7:209',
    flag: 'phase2',
  },
  {
    id: 'T03',
    name: 'Scores (optional)',
    app: 'teacher',
    path: '/record/{recordId}/scores',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '7:242',
    flag: 'phase2',
  },
  {
    id: 'T04',
    name: 'Observation (voice or text)',
    app: 'teacher',
    path: '/record/{recordId}/observation',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '7:272',
    flag: 'phase2',
  },
  {
    id: 'V01',
    name: 'Voice note — recording',
    app: 'teacher',
    path: '/record/{recordId}/voice',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '34:237',
    flag: 'phase2',
  },
  {
    id: 'V02',
    name: 'What the AI understood',
    app: 'teacher',
    path: '/record/{recordId}/understood',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '34:327',
    flag: 'phase2',
    flow: 'V01 → a voice note is processed',
  },
  {
    id: 'T07',
    name: 'Clarify student identity',
    app: 'teacher',
    path: '/record/{recordId}/identity',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '8:130',
    flag: 'phase2',
    flow: 'V02 → an unclear name',
  },
  {
    id: 'T05',
    name: 'Review before saving',
    app: 'teacher',
    path: '/record/{recordId}/review',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '7:294',
    flag: 'phase2',
  },
  {
    id: 'T06',
    name: 'Record saved',
    app: 'teacher',
    path: '/record/{recordId}/saved',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '7:317',
    flag: 'phase2',
    flow: 'T05 → Confirm',
  },
  {
    id: 'T08',
    name: 'Save failed',
    app: 'teacher',
    path: '/record/{recordId}/failed',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '8:152',
    flag: 'phase2',
    flow: 'T05 → Confirm fails',
  },
  {
    id: 'T12',
    name: 'Student detail (teacher view)',
    app: 'teacher',
    path: '/student/{studentId}',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '22:154',
    flag: 'phase2',
  },
  {
    id: 'T11',
    name: 'Add a note about a student',
    app: 'teacher',
    path: '/student/{studentId}/note',
    roles: ['teacher'],
    modes: BOTH,
    status: 'built',
    figma: '21:152',
    flag: 'phase2',
  },
  // Last: it signs in the sample teacher and changes the demo switches.
  {
    id: 'T-TRY',
    name: 'Try as a teacher (role chooser → My groups)',
    app: 'teacher',
    path: '/try?lang=ar',
    roles: ['anyone'],
    modes: DEMO,
    status: 'built',
    flow: 'W-TRY → role Teacher',
  },
];

/**
 * Fixed sample ids in the demo scenario `demo-followup` (docs/14 §5.1) and the parent fixtures.
 * Record and case ids follow the scenario's dates (`rec-<date>`), so they are read from the demo state.
 */
export const DEMO_PARAMS: Record<string, string> = {
  centreId: 'cen-nour',
  studentId: 'chd-mariam',
  centreSlug: 'al-nour-maadi',
  teacherSlug: 'salma-fathy-maths',
  enrolmentId: 'enr-mariam-phys',
  groupId: 'grp-salma-ws',
  hallId: 'hall-nour-a',
};

/** Fill `{param}`s; `null` when one has no value (the screen is only reached inside a flow). */
export function fillPath(path: string, params: Record<string, string | undefined>): string | null {
  let missing = false;
  const out = path.replace(/\{(\w+)\}/g, (_, k: string) => {
    const v = params[k];
    if (!v) missing = true;
    return v ?? '';
  });
  return missing ? null : out;
}

/** The Figma link for a node id (docs/11 §7). */
export const figmaUrl = (node: string) =>
  `https://www.figma.com/design/3TteHvTvk9JrvUthg2AyE7/?node-id=${node.replace(':', '-')}`;
