import { writeFileSync } from 'node:fs';
import { color, space, radius, elevation, fontFamily, text } from '../src/index.ts';

const lines: string[] = [];
const kebab = (s: string) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

// Names follow the Figma variables exactly (--color-blueSoft, --space-16, --radius-12).
for (const [k, v] of Object.entries(color)) lines.push(`  --color-${k}: ${v};`);
for (const [k, v] of Object.entries(space)) lines.push(`  --space-${k}: ${v}px;`);
for (const [k, v] of Object.entries(radius)) lines.push(`  --radius-${k}: ${v}px;`);
for (const [k, v] of Object.entries(elevation)) lines.push(`  --elevation-${k}: ${v};`);
lines.push(`  --font-ar: ${fontFamily.ar};`, `  --font-en: ${fontFamily.en};`);

const styles = (l: 'en' | 'ar') =>
  Object.entries(text[l]).flatMap(([k, v]) => [
    `  --text-${kebab(k)}-size: ${v.size}px;`,
    `  --text-${kebab(k)}-weight: ${v.weight};`,
    `  --text-${kebab(k)}-leading: ${v.lineHeight};`,
  ]);

const css = `/* GENERATED by packages/tokens/scripts/build-css.ts — do not edit. */
:root {
${lines.join('\n')}
  --font-ui-stack: var(--font-ar);
${styles('ar').join('\n')}
}
:root[lang='en'] {
  --font-ui-stack: var(--font-en);
${styles('en').join('\n')}
}
`;
writeFileSync(new URL('../tokens.css', import.meta.url), css);
console.log('tokens.css written');

// Tailwind v4 CSS-first theme (`@theme static` so every variable is always emitted).
// Utilities: bg-blue, text-navy, border-border, rounded-12, shadow-card, font-ui.
const theme = [
  ...Object.entries(color).map(([k, v]) => `  --color-${k}: ${v};`),
  ...Object.entries(radius).map(([k, v]) => `  --radius-${k}: ${v}px;`),
  ...Object.entries(elevation).map(([k, v]) => `  --shadow-${k}: ${v};`),
  `  --font-ui: var(--font-ui-stack);`,
];
writeFileSync(
  new URL('../theme.css', import.meta.url),
  `/* GENERATED by packages/tokens/scripts/build-css.ts — do not edit. */\n@theme static {\n${theme.join('\n')}\n}\n`,
);
console.log('theme.css written');
