/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditAuditEvents {
  action: string;
  actor_id: string | null;
  actor_type: string;
  after: Json | null;
  before: Json | null;
  centre_id: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  model_version: string | null;
  object_ref: string;
  object_type: string;
  occurred_at: Generated<Timestamp>;
  reason: string | null;
  request_id: string | null;
  trace_id: string | null;
  undoes_event_id: string | null;
}

export interface IdentityAuthSessions {
  client: string;
  created_at: Generated<Timestamp>;
  device_label: string | null;
  expires_at: Timestamp;
  family_id: string;
  id: string;
  last_used_at: Timestamp | null;
  refresh_token_hash: Buffer;
  replaced_by: string | null;
  revoked_at: Timestamp | null;
  user_id: string;
}

export interface IdentityDevices {
  app: string;
  created_at: Generated<Timestamp>;
  id: string;
  last_seen_at: Timestamp | null;
  platform: string;
  push_token: string;
  revoked_at: Timestamp | null;
  user_id: string;
}

export interface IdentityRoleAssignments {
  centre_id: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  invited_by: string | null;
  permissions: Generated<string[]>;
  revoked_at: Timestamp | null;
  role: string;
  status: Generated<string>;
  teacher_id: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface IdentityUsers {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  language: Generated<string>;
  name: string | null;
  phone_enc: Buffer;
  phone_hmac: Buffer;
  phone_last4: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface LedgerCommissionRules {
  centre_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: string;
  kind: string;
  min_amount_pt: Int8 | null;
  rate_pct: Numeric;
  reason: string | null;
  scope_id: Generated<string>;
  teacher_id: string | null;
  valid_from: Timestamp;
  valid_to: Timestamp | null;
  validity: Generated<string>;
}

export interface MarketCentresSeenByTeacher {
  area: string | null;
  id: string | null;
  name: string | null;
  verification: string | null;
}

export interface MarketGroups {
  centre_id: string;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  curriculum_id: string;
  end_time: string;
  id: string;
  monthly_fee_pt: Int8;
  offers_monthly_recurring: Generated<boolean>;
  room_booking_id: string;
  school_year_id: string;
  seat_cap: number;
  session_fee_pt: Int8;
  start_time: string;
  starts_on: Timestamp;
  status: Generated<string>;
  subject_id: string;
  teacher_id: string;
  updated_at: Generated<Timestamp>;
  weekdays: number[];
}

export interface MarketGroupSessions {
  centre_id: string;
  created_at: Generated<Timestamp>;
  ends_at: Timestamp;
  group_id: string;
  id: string;
  rent_invoice_id: string | null;
  starts_at: Timestamp;
  status: Generated<string>;
  status_changed_at: Timestamp | null;
  status_changed_by: string | null;
  status_reason: string | null;
}

export interface MarketPublicCentres {
  about_ar: string | null;
  about_en: string | null;
  address: string | null;
  area: string | null;
  governorate: string | null;
  hours: Json | null;
  id: string | null;
  location: string | null;
  location_status: string | null;
  name: string | null;
  photo_count: number | null;
  slug: string | null;
}

export interface MarketPublicGroups {
  centre_id: string | null;
  curriculum_id: string | null;
  end_time: string | null;
  id: string | null;
  monthly_fee_pt: Int8 | null;
  offers_monthly_recurring: boolean | null;
  room_booking_id: string | null;
  room_id: string | null;
  room_name: string | null;
  school_year_id: string | null;
  seat_cap: number | null;
  session_fee_pt: Int8 | null;
  start_time: string | null;
  starts_on: Timestamp | null;
  subject_id: string | null;
  teacher_id: string | null;
  weekdays: number[] | null;
}

export interface MarketPublicGroupSessions {
  ends_at: Timestamp | null;
  group_id: string | null;
  id: string | null;
  starts_at: Timestamp | null;
  status: string | null;
}

export interface MarketPublicRooms {
  capacity: number | null;
  centre_id: string | null;
  facilities: string[] | null;
  id: string | null;
  name: string | null;
  photo: number | null;
  rent_rule: Json | null;
}

export interface MarketPublicRoomSlots {
  end_time: string | null;
  room_id: string | null;
  start_time: string | null;
  taken: boolean | null;
  weekday: number | null;
}

export interface MarketPublicTeachers {
  bio_ar: string | null;
  bio_en: string | null;
  display_name: string | null;
  id: string | null;
  open_to_slots: boolean | null;
  slug: string | null;
  verified: boolean | null;
  years_experience: number | null;
}

export interface MarketReviewStats {
  distribution: Generated<number[]>;
  tag_counts: Generated<Json>;
  target_id: string;
  target_type: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketRoomBookings {
  application_id: string | null;
  centre_id: string;
  created_at: Generated<Timestamp>;
  end_reason: string | null;
  ended_by: string | null;
  ends_on: Timestamp | null;
  id: string;
  rent_rule: Json;
  room_id: string;
  starts_on: Timestamp;
  status: Generated<string>;
  teacher_id: string;
  updated_at: Generated<Timestamp>;
  weekly_slots: Json;
}

export interface MarketRoomBookingSlots {
  active_dates: string;
  booking_id: string;
  centre_id: string;
  minutes: string;
  room_id: string;
  weekday: number;
}

export interface MarketRoomOpenSlots {
  centre_id: string;
  created_at: Generated<Timestamp>;
  end_time: string;
  id: string;
  listed: Generated<boolean>;
  minutes: Generated<string>;
  room_id: string;
  start_time: string;
  weekday: number;
}

export interface MarketRooms {
  archived_at: Timestamp | null;
  capacity: number;
  centre_id: string;
  created_at: Generated<Timestamp>;
  facilities: Generated<string[]>;
  id: string;
  listed: Generated<boolean>;
  name: string;
  photo: Generated<number>;
  rent_rule: Json;
  updated_at: Generated<Timestamp>;
}

export interface MarketRoomsSeenByTeacher {
  capacity: number | null;
  centre_id: string | null;
  id: string | null;
  name: string | null;
  rent_rule: Json | null;
}

export interface MarketTeacherApplications {
  auto_approved: Generated<boolean>;
  centre_id: string;
  created_at: Generated<Timestamp>;
  decline_reason: string | null;
  expected_students: number;
  id: string;
  requested_slots: Json;
  room_booking_id: string | null;
  room_id: string;
  scheduled_contact_at: Timestamp | null;
  stage: Generated<string>;
  starts_on: Timestamp;
  subject_id: string;
  teacher_id: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketTeachersSeenByCentre {
  created_at: Timestamp | null;
  display_name: string | null;
  id: string | null;
  verified: boolean | null;
}

export interface OrgCentres {
  about_ar: string | null;
  about_en: string | null;
  address: string | null;
  archived_at: Timestamp | null;
  area: string | null;
  created_at: Generated<Timestamp>;
  governorate: string | null;
  hours: Generated<Json>;
  id: string;
  location: string | null;
  location_status: Generated<string>;
  name: string;
  owner_id: string;
  photos: Generated<Json>;
  settings: Generated<Json>;
  slug: string;
  updated_at: Generated<Timestamp>;
  verification: Generated<string>;
  verified_at: Timestamp | null;
}

export interface OrgConsentEvents {
  context: Generated<Json>;
  created_at: Generated<Timestamp>;
  granted: boolean;
  guardian_id: string | null;
  id: string;
  kind: string;
  source: string;
  student_id: string | null;
  user_id: string | null;
  version: string;
}

export interface OrgGuardians {
  created_at: Generated<Timestamp>;
  id: string;
  phone_encrypted: Buffer | null;
  phone_hmac: Buffer | null;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface OrgLeads {
  area: string | null;
  centre_name: string | null;
  contact_consent_version: string;
  converted_centre_id: string | null;
  created_at: Generated<Timestamp>;
  details: Generated<Json>;
  id: string;
  kind: string;
  last_contact_at: Timestamp | null;
  name: string | null;
  status: Generated<string>;
  teacher_count: number | null;
  updated_at: Generated<Timestamp>;
  whatsapp_encrypted: Buffer | null;
  whatsapp_hmac: Buffer | null;
}

export interface OrgStudentGuardians {
  consent_at: Timestamp;
  consent_version: string;
  created_at: Generated<Timestamp>;
  guardian_id: string;
  relation: Generated<string>;
  student_id: string;
}

export interface OrgStudents {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_guardian_id: string;
  curriculum_id: string;
  display_name: string;
  id: string;
  school_year_id: string;
  updated_at: Generated<Timestamp>;
}

export interface OrgTeachers {
  availability: Generated<Json>;
  bio_ar: string | null;
  bio_en: string | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  id: string;
  open_to_slots: Generated<boolean>;
  photo_key: string | null;
  profile_status: Generated<string>;
  settings: Generated<Json>;
  slug: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
  verification: Generated<string>;
  verified_at: Timestamp | null;
  years_experience: number | null;
}

export interface OrgTeacherSubjects {
  created_at: Generated<Timestamp>;
  subject_id: string;
  teacher_id: string;
}

export interface OrgVerificationChecks {
  check_code: string;
  created_at: Generated<Timestamp>;
  done_at: Timestamp | null;
  done_by: string | null;
  evidence_key: string | null;
  id: string;
  notes: string | null;
  status: Generated<string>;
  subject_id: string;
  subject_type: string;
  updated_at: Generated<Timestamp>;
}

export interface PlatformDataKeys {
  created_at: Generated<Timestamp>;
  key_id: string;
  purpose: string;
}

export interface PlatformFeatureFlags {
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  key: string;
  scope_id: Generated<string>;
  scope_type: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface PlatformIdempotencyKeys {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  key: string;
  method_path: string;
  request_hash: string;
  response_body: Json | null;
  response_code: number | null;
  user_id: string;
}

export interface PlatformInboxEvents {
  consumer: string;
  event_id: string;
  processed_at: Generated<Timestamp>;
}

export interface PlatformOutboxEvents {
  aggregate_id: string;
  aggregate_type: string;
  attempts: Generated<number>;
  centre_id: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  last_error: string | null;
  partition_key: string;
  payload: Json;
  published_at: Timestamp | null;
  trace_id: string | null;
  type: string;
  version: Generated<number>;
}

export interface RefAcademicTerms {
  academic_year: string;
  code: string;
  confirmed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  ends_on: Timestamp;
  id: string;
  name_ar: string;
  name_en: string;
  starts_on: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface RefCurricula {
  active: Generated<boolean>;
  code: string;
  confirmed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: string;
  name_ar: string;
  name_en: string;
  position: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface RefSchoolYears {
  code: string;
  confirmed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  curriculum_id: string;
  id: string;
  name_ar: string;
  name_en: string;
  position: Generated<number>;
  short_name_ar: string | null;
  short_name_en: string | null;
  updated_at: Generated<Timestamp>;
}

export interface RefSubjects {
  active: Generated<boolean>;
  code: string;
  confirmed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  curriculum_id: string;
  id: string;
  name_ar: string;
  name_en: string;
  school_year_id: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  "audit.audit_events": AuditAuditEvents;
  "identity.auth_sessions": IdentityAuthSessions;
  "identity.devices": IdentityDevices;
  "identity.role_assignments": IdentityRoleAssignments;
  "identity.users": IdentityUsers;
  "ledger.commission_rules": LedgerCommissionRules;
  "market.centres_seen_by_teacher": MarketCentresSeenByTeacher;
  "market.group_sessions": MarketGroupSessions;
  "market.groups": MarketGroups;
  "market.public_centres": MarketPublicCentres;
  "market.public_group_sessions": MarketPublicGroupSessions;
  "market.public_groups": MarketPublicGroups;
  "market.public_room_slots": MarketPublicRoomSlots;
  "market.public_rooms": MarketPublicRooms;
  "market.public_teachers": MarketPublicTeachers;
  "market.review_stats": MarketReviewStats;
  "market.room_booking_slots": MarketRoomBookingSlots;
  "market.room_bookings": MarketRoomBookings;
  "market.room_open_slots": MarketRoomOpenSlots;
  "market.rooms": MarketRooms;
  "market.rooms_seen_by_teacher": MarketRoomsSeenByTeacher;
  "market.teacher_applications": MarketTeacherApplications;
  "market.teachers_seen_by_centre": MarketTeachersSeenByCentre;
  "org.centres": OrgCentres;
  "org.consent_events": OrgConsentEvents;
  "org.guardians": OrgGuardians;
  "org.leads": OrgLeads;
  "org.student_guardians": OrgStudentGuardians;
  "org.students": OrgStudents;
  "org.teacher_subjects": OrgTeacherSubjects;
  "org.teachers": OrgTeachers;
  "org.verification_checks": OrgVerificationChecks;
  "platform.data_keys": PlatformDataKeys;
  "platform.feature_flags": PlatformFeatureFlags;
  "platform.idempotency_keys": PlatformIdempotencyKeys;
  "platform.inbox_events": PlatformInboxEvents;
  "platform.outbox_events": PlatformOutboxEvents;
  "ref.academic_terms": RefAcademicTerms;
  "ref.curricula": RefCurricula;
  "ref.school_years": RefSchoolYears;
  "ref.subjects": RefSubjects;
}
