/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditAuditEvents {
  action: string;
  actor_id: string | null;
  actor_type: string;
  after: Json | null;
  before: Json | null;
  centre_id: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  model_version: string | null;
  object_ref: string;
  object_type: string;
  occurred_at: Generated<Timestamp>;
  reason: string | null;
  request_id: string | null;
  trace_id: string | null;
  undoes_event_id: string | null;
}

export interface FollowupCaseAttempts {
  case_id: string;
  centre_id: string;
  channel: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  follow_up_on: Timestamp | null;
  id: string;
  learned: string | null;
  message_id: string | null;
  next_action: string | null;
  result: string;
}

export interface FollowupCaseEvents {
  actor_id: string | null;
  case_id: string;
  centre_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  kind: string;
  text_ar: string;
  text_en: string;
}

export interface FollowupCases {
  assignee_id: string;
  centre_id: string;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  dismiss_reason: string | null;
  due_on: Timestamp;
  group_id: string;
  id: string;
  outcome: string | null;
  signal_id: string;
  status: Generated<string>;
  student_id: string;
  updated_at: Generated<Timestamp>;
}

export interface FollowupRules {
  active: boolean;
  centre_id: string;
  code: string;
  created_at: Generated<Timestamp>;
  current_version: number;
  default_assignee_role: Generated<string>;
  definition: Json;
  due_in_days: Generated<number>;
  evaluated_by: Generated<string>;
  id: string;
  teacher_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface FollowupRuleVersions {
  active: boolean;
  approved_at: Timestamp | null;
  approved_by: string | null;
  centre_id: string;
  created_at: Generated<Timestamp>;
  definition: Json;
  explanation_template_ar: string;
  explanation_template_en: string;
  id: string;
  proposed_by: string | null;
  rule_id: string;
  status: string;
  version: number;
}

export interface FollowupSignals {
  centre_id: string;
  created_at: Generated<Timestamp>;
  evidence: Json;
  explanation_ar: string;
  explanation_en: string;
  group_id: string;
  id: string;
  params: Json;
  raised_at: Generated<Timestamp>;
  rule_code: string;
  rule_id: string;
  rule_version: number;
  status: Generated<string>;
  student_id: string;
  topic_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface IdentityAuthSessions {
  client: string;
  created_at: Generated<Timestamp>;
  device_label: string | null;
  expires_at: Timestamp;
  family_id: string;
  id: string;
  last_used_at: Timestamp | null;
  refresh_token_hash: Buffer;
  replaced_by: string | null;
  revoked_at: Timestamp | null;
  user_id: string;
}

export interface IdentityDevices {
  app: string;
  created_at: Generated<Timestamp>;
  id: string;
  last_seen_at: Timestamp | null;
  platform: string;
  push_token: string;
  revoked_at: Timestamp | null;
  user_id: string;
}

export interface IdentityRoleAssignments {
  centre_id: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  invited_by: string | null;
  permissions: Generated<string[]>;
  revoked_at: Timestamp | null;
  role: string;
  status: Generated<string>;
  teacher_id: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface IdentityUsers {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: string;
  language: Generated<string>;
  name: string | null;
  phone_enc: Buffer;
  phone_hmac: Buffer;
  phone_last4: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface LedgerCommissionRules {
  centre_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: string;
  kind: string;
  min_amount_pt: Int8 | null;
  rate_pct: Numeric;
  reason: string | null;
  scope_id: Generated<string>;
  teacher_id: string | null;
  valid_from: Timestamp;
  valid_to: Timestamp | null;
  validity: Generated<string>;
}

export interface LedgerLedgerAccounts {
  code: string;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  id: string;
  owner_id: string | null;
  owner_type: string;
  type: string;
}

export interface LedgerLedgerEntries {
  account_id: string;
  created_at: Generated<Timestamp>;
  credit_pt: Generated<Int8>;
  debit_pt: Generated<Int8>;
  id: string;
  payment_id: string | null;
  transaction_id: string;
}

export interface LedgerLedgerTransactions {
  centre_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string;
  id: string;
  idempotency_key: string;
  kind: string;
  occurred_at: Generated<Timestamp>;
  payment_id: string | null;
  payout_id: string | null;
  refund_id: string | null;
  rent_invoice_id: string | null;
  reverses_id: string | null;
  teacher_id: string | null;
}

export interface LedgerPaymentMandates {
  card_brand: string | null;
  card_exp_month: number | null;
  card_exp_year: number | null;
  card_last4: string | null;
  created_at: Generated<Timestamp>;
  enrolment_id: string;
  guardian_id: string;
  id: string;
  provider: string;
  provider_token_ref: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface LedgerPayments {
  amount_pt: Int8;
  card_last4: string | null;
  centre_id: string | null;
  checkout_url: string | null;
  commission_pt: Int8 | null;
  commission_rate_pct: Numeric | null;
  commission_rule_id: string | null;
  created_at: Generated<Timestamp>;
  enrolment_id: string | null;
  expires_at: Timestamp | null;
  failure_reason: string | null;
  fawry_reference: string | null;
  id: string;
  idempotency_key: string;
  kind: string;
  method: string;
  payee_id: string | null;
  payee_type: string;
  payer_user_id: string | null;
  period_end: Timestamp | null;
  period_start: Timestamp | null;
  provider: string;
  provider_ref: string | null;
  released_at: Timestamp | null;
  rent_invoice_id: string | null;
  settled_at: Timestamp | null;
  status: Generated<string>;
  subscription_id: string | null;
  succeeded_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface LedgerPayoutAccounts {
  created_at: Generated<Timestamp>;
  details_encrypted: Buffer | null;
  display_last4: string;
  holder_name_encrypted: Buffer | null;
  id: string;
  kind: string;
  owner_id: string;
  owner_type: string;
  status: Generated<string>;
  verified_at: Timestamp | null;
}

export interface LedgerProviderEvents {
  event_id: string;
  id: string;
  outcome: string | null;
  payload: Json;
  processed_at: Timestamp | null;
  provider: string;
  received_at: Generated<Timestamp>;
  signature_valid: boolean;
  type: string;
}

export interface LedgerProviderSettlementLines {
  amount_pt: Int8;
  created_at: Generated<Timestamp>;
  fee_pt: Generated<Int8>;
  id: string;
  kind: string;
  match_status: string;
  matched_payment_id: string | null;
  matched_payout_id: string | null;
  matched_refund_id: string | null;
  provider: string;
  provider_ref: string;
  raw: Json;
  settlement_date: Timestamp;
}

export interface LedgerReconciliationIssues {
  created_at: Generated<Timestamp>;
  id: string;
  kind: string;
  line_id: string | null;
  provider: string;
  resolution: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  status: Generated<string>;
}

export interface LedgerRefunds {
  amount_pt: Int8;
  approved_at: Timestamp | null;
  approved_by: string | null;
  auto_eligible: Generated<boolean>;
  commission_reversed_pt: Generated<Int8>;
  created_at: Generated<Timestamp>;
  destination: Generated<string>;
  enrolment_id: string | null;
  id: string;
  idempotency_key: string;
  payment_id: string;
  policy: string;
  provider_ref: string | null;
  reason: string | null;
  requested_by: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface LedgerRentInvoices {
  calculation: Generated<Json>;
  centre_id: string;
  commission_rule_id: string | null;
  created_at: Generated<Timestamp>;
  deducted_pt: Generated<Int8>;
  due_on: Timestamp | null;
  fees_base_adjustment_pt: Generated<Int8>;
  fees_base_carried_pt: Generated<Int8>;
  fees_base_pt: Generated<Int8>;
  gross_amount_pt: Int8;
  id: string;
  issued_at: Timestamp | null;
  link_fee_amount_pt: Int8;
  link_fee_pct: Numeric;
  net_to_centre_pt: Int8;
  period: string;
  room_booking_id: string;
  sessions_count: Generated<number>;
  settled_at: Timestamp | null;
  status: Generated<string>;
  student_sessions_count: Generated<number>;
  teacher_id: string;
  topup_paid_pt: Generated<Int8>;
  updated_at: Generated<Timestamp>;
}

export interface MarketCentresSeenByTeacher {
  area: string | null;
  id: string | null;
  name: string | null;
  verification: string | null;
}

export interface MarketEnrolmentPeople {
  centre_id: string | null;
  enrolment_id: string | null;
  group_id: string | null;
  guardian_name: string | null;
  school_year_id: string | null;
  student_name: string | null;
  teacher_id: string | null;
}

export interface MarketEnrolments {
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  centre_id: string;
  consent_event_id: string | null;
  created_at: Generated<Timestamp>;
  current_period_end: Timestamp | null;
  current_period_start: Timestamp | null;
  first_session_id: string;
  group_id: string;
  guardian_id: string;
  hold_expires_at: Timestamp | null;
  id: string;
  idempotency_key: string | null;
  method: string | null;
  payment_plan: string;
  phone_shared: Generated<boolean>;
  plan_cancelled_at: Timestamp | null;
  price_pt: Int8;
  reference: Generated<string>;
  session_id: string | null;
  status: string;
  status_changed_at: Generated<Timestamp>;
  student_id: string;
  teacher_id: string;
  teacher_reviews: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  waitlist_entry_id: string | null;
}

export interface MarketGroups {
  centre_id: string;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  curriculum_id: string;
  end_time: string;
  id: string;
  monthly_fee_pt: Int8;
  offers_monthly_recurring: Generated<boolean>;
  room_booking_id: string;
  school_year_id: string;
  seat_cap: number;
  session_fee_pt: Int8;
  start_time: string;
  starts_on: Timestamp;
  status: Generated<string>;
  subject_id: string;
  teacher_id: string;
  updated_at: Generated<Timestamp>;
  weekdays: number[];
}

export interface MarketGroupSessions {
  centre_id: string;
  created_at: Generated<Timestamp>;
  ends_at: Timestamp;
  group_id: string;
  id: string;
  rent_invoice_id: string | null;
  starts_at: Timestamp;
  status: Generated<string>;
  status_changed_at: Timestamp | null;
  status_changed_by: string | null;
  status_reason: string | null;
}

export interface MarketPublicCentres {
  about_ar: string | null;
  about_en: string | null;
  address: string | null;
  area: string | null;
  governorate: string | null;
  hours: Json | null;
  id: string | null;
  location: string | null;
  location_status: string | null;
  name: string | null;
  photo_count: number | null;
  slug: string | null;
}

export interface MarketPublicGroups {
  centre_id: string | null;
  curriculum_id: string | null;
  end_time: string | null;
  id: string | null;
  monthly_fee_pt: Int8 | null;
  offers_monthly_recurring: boolean | null;
  room_booking_id: string | null;
  room_id: string | null;
  room_name: string | null;
  school_year_id: string | null;
  seat_cap: number | null;
  session_fee_pt: Int8 | null;
  start_time: string | null;
  starts_on: Timestamp | null;
  subject_id: string | null;
  teacher_id: string | null;
  weekdays: number[] | null;
}

export interface MarketPublicGroupSessions {
  ends_at: Timestamp | null;
  group_id: string | null;
  id: string | null;
  starts_at: Timestamp | null;
  status: string | null;
}

export interface MarketPublicRooms {
  capacity: number | null;
  centre_id: string | null;
  facilities: string[] | null;
  id: string | null;
  name: string | null;
  photo: number | null;
  rent_rule: Json | null;
}

export interface MarketPublicRoomSlots {
  end_time: string | null;
  room_id: string | null;
  start_time: string | null;
  taken: boolean | null;
  weekday: number | null;
}

export interface MarketPublicTeachers {
  bio_ar: string | null;
  bio_en: string | null;
  display_name: string | null;
  id: string | null;
  open_to_slots: boolean | null;
  slug: string | null;
  verified: boolean | null;
  years_experience: number | null;
}

export interface MarketReviewReplies {
  author_user_id: string;
  body: string;
  centre_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  review_id: string;
  status: Generated<string>;
}

export interface MarketReviewReports {
  centre_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  reason: string;
  reported_by: string;
  resolution: string | null;
  resolved_at: Timestamp | null;
  review_id: string;
}

export interface MarketReviews {
  body: Generated<string>;
  centre_id: string;
  created_at: Generated<Timestamp>;
  enrolment_id: string;
  flags: Generated<string[]>;
  guardian_id: string;
  id: string;
  published_at: Timestamp | null;
  school_year_id: string;
  stars: number;
  status: string;
  tags: Generated<string[]>;
  target_id: string;
  target_type: string;
  term_id: string | null;
  updated_at: Generated<Timestamp>;
  visibility: string;
}

export interface MarketReviewStats {
  distribution: Generated<number[]>;
  tag_counts: Generated<Json>;
  target_id: string;
  target_type: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketRoomBookings {
  application_id: string | null;
  centre_id: string;
  created_at: Generated<Timestamp>;
  end_reason: string | null;
  ended_by: string | null;
  ends_on: Timestamp | null;
  id: string;
  rent_rule: Json;
  room_id: string;
  starts_on: Timestamp;
  status: Generated<string>;
  teacher_id: string;
  updated_at: Generated<Timestamp>;
  weekly_slots: Json;
}

export interface MarketRoomBookingSlots {
  active_dates: string;
  booking_id: string;
  centre_id: string;
  minutes: string;
  room_id: string;
  weekday: number;
}

export interface MarketRoomOpenSlots {
  centre_id: string;
  created_at: Generated<Timestamp>;
  end_time: string;
  id: string;
  listed: Generated<boolean>;
  minutes: Generated<string>;
  room_id: string;
  start_time: string;
  weekday: number;
}

export interface MarketRooms {
  archived_at: Timestamp | null;
  capacity: number;
  centre_id: string;
  created_at: Generated<Timestamp>;
  facilities: Generated<string[]>;
  id: string;
  listed: Generated<boolean>;
  name: string;
  photo: Generated<number>;
  rent_rule: Json;
  updated_at: Generated<Timestamp>;
}

export interface MarketRoomsSeenByTeacher {
  capacity: number | null;
  centre_id: string | null;
  id: string | null;
  name: string | null;
  rent_rule: Json | null;
}

export interface MarketTeacherApplications {
  auto_approved: Generated<boolean>;
  centre_id: string;
  created_at: Generated<Timestamp>;
  decline_reason: string | null;
  expected_students: number;
  id: string;
  requested_slots: Json;
  room_booking_id: string | null;
  room_id: string;
  scheduled_contact_at: Timestamp | null;
  stage: Generated<string>;
  starts_on: Timestamp;
  subject_id: string;
  teacher_id: string;
  updated_at: Generated<Timestamp>;
}

export interface MarketTeachersSeenByCentre {
  created_at: Timestamp | null;
  display_name: string | null;
  id: string | null;
  verified: boolean | null;
}

export interface MarketWaitlistEntries {
  centre_id: string;
  created_at: Generated<Timestamp>;
  enrolment_id: string | null;
  group_id: string;
  guardian_id: string;
  id: string;
  offer_expires_at: Timestamp | null;
  offered_at: Timestamp | null;
  offered_sessions: string[] | null;
  status: Generated<string>;
  student_id: string;
  updated_at: Generated<Timestamp>;
}

export interface MessagingInboundMessages {
  body: string;
  centre_id: string;
  channel: string;
  created_at: Generated<Timestamp>;
  guardian_id: string;
  id: string;
  intent: string | null;
  is_stop: Generated<boolean>;
  message_id: string | null;
  provider_message_id: string;
  received_at: Timestamp;
  summary: string | null;
}

export interface MessagingMessages {
  approved_at: Timestamp | null;
  approved_by: string | null;
  case_id: string | null;
  centre_id: string;
  channel: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  delivery_status: Generated<string>;
  draft: string;
  failure_reason: string | null;
  final_text: string | null;
  focus_plan_id: string | null;
  grounded_facts: Generated<Json>;
  group_id: string | null;
  guardian_id: string;
  id: string;
  language: Generated<string>;
  provider: string | null;
  provider_message_id: string | null;
  purpose: string;
  reply: string | null;
  reply_intent: string | null;
  revises_id: string | null;
  sent_manually_at: Timestamp | null;
  sent_manually_by: string | null;
  student_id: string;
  template_code: string | null;
  tone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface MessagingMessageStatusEvents {
  centre_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  message_id: string;
  provider_event_id: string | null;
  status: string;
}

export interface MessagingNotificationLog {
  channel: string;
  created_at: Generated<Timestamp>;
  event_id: string;
  id: string;
  provider_ref: string | null;
  status: string;
  template_code: string;
  user_id: string;
}

export interface OrgCentres {
  about_ar: string | null;
  about_en: string | null;
  address: string | null;
  archived_at: Timestamp | null;
  area: string | null;
  created_at: Generated<Timestamp>;
  governorate: string | null;
  hours: Generated<Json>;
  id: string;
  location: string | null;
  location_status: Generated<string>;
  name: string;
  owner_id: string;
  photos: Generated<Json>;
  settings: Generated<Json>;
  slug: string;
  updated_at: Generated<Timestamp>;
  verification: Generated<string>;
  verified_at: Timestamp | null;
}

export interface OrgConsentEvents {
  context: Generated<Json>;
  created_at: Generated<Timestamp>;
  granted: boolean;
  guardian_id: string | null;
  id: string;
  kind: string;
  source: string;
  student_id: string | null;
  user_id: string | null;
  version: string;
}

export interface OrgGuardians {
  created_at: Generated<Timestamp>;
  home_area: string | null;
  id: string;
  phone_encrypted: Buffer | null;
  phone_hmac: Buffer | null;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface OrgLeads {
  area: string | null;
  centre_name: string | null;
  contact_consent_version: string;
  converted_centre_id: string | null;
  created_at: Generated<Timestamp>;
  details: Generated<Json>;
  id: string;
  kind: string;
  last_contact_at: Timestamp | null;
  name: string | null;
  status: Generated<string>;
  teacher_count: number | null;
  updated_at: Generated<Timestamp>;
  whatsapp_encrypted: Buffer | null;
  whatsapp_hmac: Buffer | null;
}

export interface OrgStudentGuardians {
  consent_at: Timestamp;
  consent_version: string;
  created_at: Generated<Timestamp>;
  guardian_id: string;
  relation: Generated<string>;
  student_id: string;
}

export interface OrgStudents {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_guardian_id: string;
  curriculum_id: string;
  display_name: string;
  id: string;
  school_year_id: string;
  updated_at: Generated<Timestamp>;
}

export interface OrgTeachers {
  availability: Generated<Json>;
  bio_ar: string | null;
  bio_en: string | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  id: string;
  open_to_slots: Generated<boolean>;
  photo_key: string | null;
  profile_status: Generated<string>;
  settings: Generated<Json>;
  slug: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
  verification: Generated<string>;
  verified_at: Timestamp | null;
  years_experience: number | null;
}

export interface OrgTeacherSubjects {
  created_at: Generated<Timestamp>;
  subject_id: string;
  teacher_id: string;
}

export interface OrgVerificationChecks {
  check_code: string;
  created_at: Generated<Timestamp>;
  done_at: Timestamp | null;
  done_by: string | null;
  evidence_key: string | null;
  id: string;
  notes: string | null;
  status: Generated<string>;
  subject_id: string;
  subject_type: string;
  updated_at: Generated<Timestamp>;
}

export interface PlatformDataKeys {
  created_at: Generated<Timestamp>;
  key_id: string;
  purpose: string;
}

export interface PlatformFeatureFlags {
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  key: string;
  scope_id: Generated<string>;
  scope_type: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface PlatformIdempotencyKeys {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  key: string;
  method_path: string;
  request_hash: string;
  response_body: Json | null;
  response_code: number | null;
  user_id: string;
}

export interface PlatformInboxEvents {
  consumer: string;
  event_id: string;
  processed_at: Generated<Timestamp>;
}

export interface PlatformOutboxEvents {
  aggregate_id: string;
  aggregate_type: string;
  attempts: Generated<number>;
  centre_id: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  last_error: string | null;
  partition_key: string;
  payload: Json;
  published_at: Timestamp | null;
  trace_id: string | null;
  type: string;
  version: Generated<number>;
}

export interface RecordsAssessmentItems {
  assessment_id: string;
  centre_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  label: string;
  max_marks: Numeric;
  position: number;
}

export interface RecordsAssessments {
  centre_id: string;
  created_at: Generated<Timestamp>;
  group_id: string;
  id: string;
  max_score: Numeric;
  series: string | null;
  session_record_id: string | null;
  tagging_mode: Generated<string>;
  taken_on: Timestamp;
  title: string;
}

export interface RecordsCorrectionRequests {
  centre_id: string;
  created_at: Generated<Timestamp>;
  done_at: Timestamp | null;
  group_id: string;
  id: string;
  requested_by: string;
  session_record_id: string;
  status: Generated<string>;
  student_id: string | null;
  text: string;
}

export interface RecordsCorrections {
  centre_id: string;
  corrected_by: string;
  created_at: Generated<Timestamp>;
  field: string;
  id: string;
  new_value: string | null;
  old_value: string | null;
  reason: string;
  record_entry_id: string;
  session_record_id: string;
  student_id: string;
}

export interface RecordsItemScores {
  assessment_item_id: string;
  centre_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  marks: Numeric;
  record_entry_id: string | null;
  student_id: string;
}

export interface RecordsKnownStudents {
  centre_id: string | null;
  display_name: string | null;
  group_id: string | null;
  student_id: string | null;
}

export interface RecordsNotes {
  author_id: string;
  body: string;
  centre_id: string;
  created_at: Generated<Timestamp>;
  group_id: string;
  id: string;
  session_record_id: string | null;
  student_id: string;
  tag: string;
  updated_at: Generated<Timestamp>;
  visibility: Generated<string>;
}

export interface RecordsRecordEntries {
  assessment_id: string | null;
  attendance: Generated<string>;
  centre_id: string;
  confidence: Json | null;
  created_at: Generated<Timestamp>;
  homework: Generated<string>;
  id: string;
  late_minutes: number | null;
  observation: string | null;
  observation_tag: string | null;
  participation: Generated<string>;
  score: Numeric | null;
  session_record_id: string;
  source: Generated<string>;
  source_spans: Json | null;
  student_id: string;
  updated_at: Generated<Timestamp>;
}

export interface RecordsSessionRecords {
  centre_id: string;
  confirmed_at: Timestamp | null;
  confirmed_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  group_id: string;
  group_observation: string | null;
  group_session_id: string;
  id: string;
  idempotency_key: string | null;
  session_date: Timestamp;
  source: Generated<string>;
  status: Generated<string>;
  teacher_id: string;
  updated_at: Generated<Timestamp>;
}

export interface RecordsVoiceExtractions {
  centre_id: string;
  created_at: Generated<Timestamp>;
  discarded: Generated<string[]>;
  id: string;
  model_version: string | null;
  proposal: Json | null;
  resolved: Generated<Json>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  voice_note_id: string;
}

export interface RecordsVoiceNotes {
  audio_bytes: number | null;
  audio_key: string | null;
  audio_mime: string | null;
  centre_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  data_class: string;
  delete_after: Timestamp | null;
  duration_s: number;
  eta_seconds: number | null;
  failure_code: string | null;
  id: string;
  idempotency_key: string | null;
  model_version: string | null;
  session_record_id: string;
  status: Generated<string>;
  stt_provider: string | null;
  submitted_at: Timestamp | null;
  teacher_id: string;
  transcript: string | null;
  transcript_delete_after: Timestamp | null;
  updated_at: Generated<Timestamp>;
  uploaded_at: Timestamp | null;
}

export interface RefAcademicTerms {
  academic_year: string;
  code: string;
  confirmed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  ends_on: Timestamp;
  id: string;
  name_ar: string;
  name_en: string;
  starts_on: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface RefCurricula {
  active: Generated<boolean>;
  code: string;
  confirmed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: string;
  name_ar: string;
  name_en: string;
  position: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface RefSchoolYears {
  code: string;
  confirmed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  curriculum_id: string;
  id: string;
  name_ar: string;
  name_en: string;
  position: Generated<number>;
  short_name_ar: string | null;
  short_name_en: string | null;
  updated_at: Generated<Timestamp>;
}

export interface RefSubjects {
  active: Generated<boolean>;
  code: string;
  confirmed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  curriculum_id: string;
  id: string;
  name_ar: string;
  name_en: string;
  school_year_id: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  "audit.audit_events": AuditAuditEvents;
  "followup.case_attempts": FollowupCaseAttempts;
  "followup.case_events": FollowupCaseEvents;
  "followup.cases": FollowupCases;
  "followup.rule_versions": FollowupRuleVersions;
  "followup.rules": FollowupRules;
  "followup.signals": FollowupSignals;
  "identity.auth_sessions": IdentityAuthSessions;
  "identity.devices": IdentityDevices;
  "identity.role_assignments": IdentityRoleAssignments;
  "identity.users": IdentityUsers;
  "ledger.commission_rules": LedgerCommissionRules;
  "ledger.ledger_accounts": LedgerLedgerAccounts;
  "ledger.ledger_entries": LedgerLedgerEntries;
  "ledger.ledger_transactions": LedgerLedgerTransactions;
  "ledger.payment_mandates": LedgerPaymentMandates;
  "ledger.payments": LedgerPayments;
  "ledger.payout_accounts": LedgerPayoutAccounts;
  "ledger.provider_events": LedgerProviderEvents;
  "ledger.provider_settlement_lines": LedgerProviderSettlementLines;
  "ledger.reconciliation_issues": LedgerReconciliationIssues;
  "ledger.refunds": LedgerRefunds;
  "ledger.rent_invoices": LedgerRentInvoices;
  "market.centres_seen_by_teacher": MarketCentresSeenByTeacher;
  "market.enrolment_people": MarketEnrolmentPeople;
  "market.enrolments": MarketEnrolments;
  "market.group_sessions": MarketGroupSessions;
  "market.groups": MarketGroups;
  "market.public_centres": MarketPublicCentres;
  "market.public_group_sessions": MarketPublicGroupSessions;
  "market.public_groups": MarketPublicGroups;
  "market.public_room_slots": MarketPublicRoomSlots;
  "market.public_rooms": MarketPublicRooms;
  "market.public_teachers": MarketPublicTeachers;
  "market.review_replies": MarketReviewReplies;
  "market.review_reports": MarketReviewReports;
  "market.review_stats": MarketReviewStats;
  "market.reviews": MarketReviews;
  "market.room_booking_slots": MarketRoomBookingSlots;
  "market.room_bookings": MarketRoomBookings;
  "market.room_open_slots": MarketRoomOpenSlots;
  "market.rooms": MarketRooms;
  "market.rooms_seen_by_teacher": MarketRoomsSeenByTeacher;
  "market.teacher_applications": MarketTeacherApplications;
  "market.teachers_seen_by_centre": MarketTeachersSeenByCentre;
  "market.waitlist_entries": MarketWaitlistEntries;
  "messaging.inbound_messages": MessagingInboundMessages;
  "messaging.message_status_events": MessagingMessageStatusEvents;
  "messaging.messages": MessagingMessages;
  "messaging.notification_log": MessagingNotificationLog;
  "org.centres": OrgCentres;
  "org.consent_events": OrgConsentEvents;
  "org.guardians": OrgGuardians;
  "org.leads": OrgLeads;
  "org.student_guardians": OrgStudentGuardians;
  "org.students": OrgStudents;
  "org.teacher_subjects": OrgTeacherSubjects;
  "org.teachers": OrgTeachers;
  "org.verification_checks": OrgVerificationChecks;
  "platform.data_keys": PlatformDataKeys;
  "platform.feature_flags": PlatformFeatureFlags;
  "platform.idempotency_keys": PlatformIdempotencyKeys;
  "platform.inbox_events": PlatformInboxEvents;
  "platform.outbox_events": PlatformOutboxEvents;
  "records.assessment_items": RecordsAssessmentItems;
  "records.assessments": RecordsAssessments;
  "records.correction_requests": RecordsCorrectionRequests;
  "records.corrections": RecordsCorrections;
  "records.item_scores": RecordsItemScores;
  "records.known_students": RecordsKnownStudents;
  "records.notes": RecordsNotes;
  "records.record_entries": RecordsRecordEntries;
  "records.session_records": RecordsSessionRecords;
  "records.voice_extractions": RecordsVoiceExtractions;
  "records.voice_notes": RecordsVoiceNotes;
  "ref.academic_terms": RefAcademicTerms;
  "ref.curricula": RefCurricula;
  "ref.school_years": RefSchoolYears;
  "ref.subjects": RefSubjects;
}
