// node scripts/build-logo.mjs — Link logo assets (Figma 65:385).
// Orb: a raster in Figma (no vector source yet; open item in docs/13). From the @3x PNG exports in
// packages/ui/src/brand/source we write 1x/2x/3x PNG + WebP for web (<picture>) and the RN density
// variants (name.png, name@2x.png, name@3x.png). Nothing is wrapped in SVG.
// Wordmark: "link." outlined from Plus Jakarta Sans Bold (SIL OFL 1.1 — outlining glyphs in artwork
// is permitted) at the Figma spec: 24 px, letter-spacing −2%.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createRequire } from 'node:module';
import sharp from 'sharp';
import opentype from 'opentype.js';
import { ROOT } from './lib/env.mjs';

const BRAND = join(ROOT, 'packages', 'ui', 'src', 'brand');
const NATIVE = join(ROOT, 'packages', 'ui-native', 'src', 'brand');
mkdirSync(NATIVE, { recursive: true });

const orbs = [
  { name: 'logo-mark', base: 48 },
  { name: 'logo-mark-halo', base: 96 },
];
for (const { name, base } of orbs) {
  // The Figma exports sit on an opaque white square; a circular alpha mask removes only that square
  // (the orb and its halo are round), so the mark also works on dark surfaces (V01).
  const raw = readFileSync(join(BRAND, 'source', `${name}@3x.png`));
  const { width: w = 0 } = await sharp(raw).metadata();
  const mask = Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${w}"><circle cx="${w / 2}" cy="${w / 2}" r="${w / 2 - 0.5}" fill="#fff"/></svg>`,
  );
  const src = await sharp(raw)
    .ensureAlpha()
    .composite([{ input: mask, blend: 'dest-in' }])
    .png()
    .toBuffer();
  for (const scale of [1, 2, 3]) {
    const px = base * scale;
    const img = sharp(src).resize(px, px, { kernel: 'lanczos3' });
    await img
      .clone()
      .png({ compressionLevel: 9 })
      .toFile(join(BRAND, `${name}@${scale}x.png`));
    await img
      .clone()
      .webp({ quality: 90, alphaQuality: 100 })
      .toFile(join(BRAND, `${name}@${scale}x.webp`));
    await img
      .clone()
      .png({ compressionLevel: 9 })
      .toFile(join(NATIVE, scale === 1 ? `${name}.png` : `${name}@${scale}x.png`));
  }
}

// Wordmark paths.
const require = createRequire(join(ROOT, 'packages', 'ui', 'package.json'));
const fontFile =
  require.resolve('@fontsource/plus-jakarta-sans/files/plus-jakarta-sans-latin-700-normal.woff');
const buf = readFileSync(fontFile);
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
const SIZE = 24;
const TRACKING = -0.02 * SIZE;
const text = 'link.';
// Map characters directly: plain lowercase needs no GSUB substitutions (opentype.js cannot run this font's ccmp table).
const glyphs = [...text].map((ch) => font.charToGlyph(ch));
const scale = SIZE / font.unitsPerEm;
const ascent = font.ascender * scale;
let x = 0;
const d = [];
glyphs.forEach((g, i) => {
  d.push(g.getPath(x, ascent, SIZE).toPathData(2));
  const kern = i < glyphs.length - 1 ? font.getKerningValue(g, glyphs[i + 1]) * scale : 0;
  x += g.advanceWidth * scale + kern + (i < glyphs.length - 1 ? TRACKING : 0);
});
const height = Math.ceil((font.ascender - font.descender) * scale);
const width = Math.ceil(x);
const wordmarkTs = `// GENERATED by scripts/build-logo.mjs from Plus Jakarta Sans Bold (SIL OFL 1.1). Do not edit.
// "link." at 24 px with −2% letter-spacing (Figma 65:380). Fill with currentColor.
export const WORDMARK = { width: ${width}, height: ${height}, d: ${JSON.stringify(d.join(' '))} } as const;
`;
for (const dir of [BRAND, NATIVE]) writeFileSync(join(dir, 'wordmark.ts'), wordmarkTs);
console.log(`orbs: 2 × 3 densities (PNG + WebP, RN PNG); wordmark ${width}×${height}`);
