// node scripts/env-local.mjs [--force] — write a fresh .env.local for this machine (or CI):
// the standard local ports and URLs, and random secrets that never leave the file. It refuses to
// overwrite an existing .env.local unless --force. Sample-data local stack only (docs/14 §3).
import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { ENV_FILE, fail } from './lib/env.mjs';

if (existsSync(ENV_FILE) && !process.argv.includes('--force'))
  fail('.env.local exists; pass --force to replace it (its secrets and local data keys change).');

const secret = (bytes = 24) => randomBytes(bytes).toString('base64url');
const key32 = () => randomBytes(32).toString('base64');
const pw = {
  postgres: secret(),
  migrator: secret(),
  user: secret(),
  worker: secret(),
  ops: secret(),
};
const PG = process.env.POSTGRES_HOST_PORT || '5432';
const db = (role, pass) => `postgres://${role}:${pass}@localhost:${PG}/link`;

const values = {
  APP_ENV: 'local',
  LOG_LEVEL: 'info',
  POSTGRES_HOST_PORT: PG,
  POSTGRES_PASSWORD: pw.postgres,
  APP_MIGRATOR_PASSWORD: pw.migrator,
  APP_USER_PASSWORD: pw.user,
  APP_WORKER_PASSWORD: pw.worker,
  APP_OPS_PASSWORD: pw.ops,
  DATABASE_URL: db('app_user', pw.user),
  DATABASE_URL_WORKER: db('app_worker', pw.worker),
  DATABASE_URL_OPS: db('app_ops', pw.ops),
  DATABASE_URL_MIGRATOR: db('app_migrator', pw.migrator),
  DATABASE_REPLICA_URL: db('app_user', pw.user),
  REDIS_CACHE_URL: 'redis://localhost:6379/0',
  REDIS_STATE_URL: 'redis://localhost:6380/0',
  AWS_ACCESS_KEY_ID: 'local',
  AWS_SECRET_ACCESS_KEY: 'local',
  AWS_ENDPOINT_URL: 'http://localhost:4566',
  S3_ENDPOINT: 'http://localhost:4566',
  S3_REGION: 'eu-central-1',
  S3_BUCKET_VOICE: 'link-local-voice',
  S3_BUCKET_MEDIA: 'link-local-media',
  S3_BUCKET_EXPORTS: 'link-local-exports',
  KMS_KEY_STORAGE: 'alias/link-local-storage',
  KMS_KEY_FIELDS: 'alias/link-local-fields',
  HMAC_KEY_LOOKUP: secret(32),
  FIELD_KEY_LOCAL: key32(),
  QUEUE_PROVIDER: 'sqs',
  EVENTS_TOPIC: 'link-local-events',
  QUEUE_NOTIFICATIONS: 'link-local-notifications',
  DLQ_NOTIFICATIONS: 'link-local-notifications-dlq',
  QUEUE_PLATFORM_DEMO: 'link-local-platform-demo',
  DLQ_PLATFORM_DEMO: 'link-local-platform-demo-dlq',
  JWT_ISSUER: 'http://localhost:4000',
  JWT_AUDIENCE: 'link-local',
  JWT_SIGNING_KEY_ID: 'local-dev',
  JWT_SIGNING_KEY: key32(),
  ACCESS_TOKEN_TTL: '900',
  REFRESH_TOKEN_TTL: '2592000',
  CORE_API_PORT: '4000',
  CORE_API_URL: 'http://localhost:4000',
  CORS_ALLOWED_ORIGINS: 'http://localhost:8081',
  SMS_PROVIDER: 'fake',
  SMS_SENDER_ID: 'Link',
  SMS_SINK_HOST_PORT: '8093',
  SMS_SINK_URL: 'http://localhost:8093',
  PAYMENT_PROVIDER: 'fake',
  PAYMENT_WEBHOOK_SECRET: secret(),
  FAKE_PAY_URL: 'http://localhost:8091',
  FAKE_PAY_WEBHOOK_URL: 'http://host.docker.internal:4000/v1/webhooks/payments/fake-pay',
  EMAIL_PROVIDER: 'fake',
};

const body = Object.entries(values)
  .map(([k, v]) => `${k}=${v}`)
  .join('\n');
writeFileSync(
  ENV_FILE,
  `# Generated by scripts/env-local.mjs — local sample stack only. Never commit this file.\n${body}\n`,
);
console.log(`✔ Wrote .env.local (${Object.keys(values).length} values, fresh secrets).`);
