#!/usr/bin/env node
// Landing page icons: one SVG sprite from the Figma icon exports.
//
//   node scripts/landing-sprite.mjs
//
// Reads apps/web/public/landing/figma/i/*.svg (Figma's own exports, unchanged) and writes
// apps/web/public/landing/figma/icons.svg: one <symbol> per icon, ids inside prefixed per icon.
// The page draws each icon with <use href="…/icons.svg#name">: one cached request instead of one
// per icon, and no icon markup in the HTML. The decorations drawn as images are left out.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIR = join(ROOT, 'apps/web/public/landing/figma');
export const DECOR = new Set([
  'hero-glow',
  'hero-ring1',
  'hero-ring2',
  'hero-sat1',
  'hero-sat2',
  'hero-sat3',
  'how-track',
  'how-traveler',
  'trust-connector',
  'cta-ring1',
  'cta-ring2',
]);

const symbols = [];
for (const file of readdirSync(join(DIR, 'i'))
  .filter((f) => f.endsWith('.svg'))
  .sort()) {
  const id = file.replace(/\.svg$/, '');
  if (DECOR.has(id)) continue;
  const raw = readFileSync(join(DIR, 'i', file), 'utf8');
  const viewBox = raw.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error(`${file}: no viewBox`);
  const p = `${id}-`;
  const inner = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\sid="([^"]+)"/g, ` id="${p}$1"`)
    .replace(/url\(#([^)]+)\)/g, `url(#${p}$1)`)
    .replace(/href="#([^"]+)"/g, `href="#${p}$1"`)
    .trim();
  symbols.push(`<symbol id="${id}" viewBox="${viewBox}">${inner}</symbol>`);
}
const sprite = `<svg xmlns="http://www.w3.org/2000/svg">${symbols.join('')}</svg>\n`;
writeFileSync(join(DIR, 'icons.svg'), sprite);
const hash = createHash('sha256').update(sprite).digest('hex').slice(0, 8);
writeFileSync(
  join(ROOT, 'apps/web/src/site/landing/sprite.ts'),
  `// Generated by scripts/landing-sprite.mjs: the sprite's content hash, for cache busting.\nexport const SPRITE = '/landing/figma/icons.svg?v=${hash}';\n`,
);
console.log(`${symbols.length} icons, ${sprite.length} bytes, v=${hash}`);
